/* Copyright Statement:
 *
 * (C) 2005-2016  MediaTek Inc. All rights reserved.
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. ("MediaTek") and/or its licensors.
 * Without the prior written permission of MediaTek and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) MediaTek Software
 * if you have agreed to and been bound by the applicable license agreement with
 * MediaTek ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of MediaTek Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT MEDIATEK SOFTWARE RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

#ifndef __HAL_PMU_PLATFORM_MT2625_H__
#define __HAL_PMU_PLATFORM_MT2625_H__

#define PMU_REG_BASE (0xA2070000)

#define PMU_DIG_TOP_CON0        ((uint32_t)(PMU_REG_BASE+0x0000))
#define PMU_DIG_TOP_CON1        ((uint32_t)(PMU_REG_BASE+0x0004))
#define PMU_DIG_TOP_CON2        ((uint32_t)(PMU_REG_BASE+0x0008))
#define PMU_DIG_TOP_TEST_CON0   ((uint32_t)(PMU_REG_BASE+0x000C))
#define PMU_DIG_TOP_MON0        ((uint32_t)(PMU_REG_BASE+0x0010))
#define PMU_DIG_TOP_MON1        ((uint32_t)(PMU_REG_BASE+0x0014))
#define PMU_DIG_TOP_MON2        ((uint32_t)(PMU_REG_BASE+0x0018))
#define PMU_DIG_TOP_MON3        ((uint32_t)(PMU_REG_BASE+0x001C))
#define PMU_DIG_TOP_MON4        ((uint32_t)(PMU_REG_BASE+0x0020))
#define PMU_DIG_TOP_MON5        ((uint32_t)(PMU_REG_BASE+0x0024))
#define PMU_DIG_TOP_MON6        ((uint32_t)(PMU_REG_BASE+0x0028))
#define PMU_DIG_TOP_MON7        ((uint32_t)(PMU_REG_BASE+0x002C))
#define PMU_DIG_TOP_MON8        ((uint32_t)(PMU_REG_BASE+0x0030))
#define PMU_DIG_TOP_MON9        ((uint32_t)(PMU_REG_BASE+0x0034))
#define PMU_DIG_TOP_MON10       ((uint32_t)(PMU_REG_BASE+0x0038))
#define PMU_DIG_TOP_MON11       ((uint32_t)(PMU_REG_BASE+0x003C))
#define PMU_DIG_TOP_MON12       ((uint32_t)(PMU_REG_BASE+0x0040))
#define PMU_DIG_TOP_MON13       ((uint32_t)(PMU_REG_BASE+0x0044))
#define PMU_DIG_TOP_MON14       ((uint32_t)(PMU_REG_BASE+0x0048))
#define PMU_DIG_INT_MISC        ((uint32_t)(PMU_REG_BASE+0x0200))
#define PMU_DIG_INT_STATUS      ((uint32_t)(PMU_REG_BASE+0x0204))
#define PMU_DIG_INT_RAW_STATUS  ((uint32_t)(PMU_REG_BASE+0x0208))
#define PMU_DIG_INT_STATUS_CLR  ((uint32_t)(PMU_REG_BASE+0x020C))
#define PMU_DIG_INT_EN_CON      ((uint32_t)(PMU_REG_BASE+0x0210))
#define PMU_DIG_INT_MASK_CON    ((uint32_t)(PMU_REG_BASE+0x0214))
#define PMU_DIG_DEG_CFG_VCORE   ((uint32_t)(PMU_REG_BASE+0x0218))
#define PMU_DIG_DEG_CFG_VRF     ((uint32_t)(PMU_REG_BASE+0x021C))
#define PMU_DIG_DEG_CFG_VPA     ((uint32_t)(PMU_REG_BASE+0x0220))
#define PMU_DIG_DEG_CFG_VIO18_0 ((uint32_t)(PMU_REG_BASE+0x0224))
#define PMU_DIG_DEG_CFG_VIO18_1 ((uint32_t)(PMU_REG_BASE+0x0228))
#define PMU_DIG_DEG_CFG_VSRAM_0 ((uint32_t)(PMU_REG_BASE+0x022C))
#define PMU_DIG_DEG_CFG_VSRAM_1 ((uint32_t)(PMU_REG_BASE+0x0230))
#define PMU_DIG_DEG_CFG_VFEM_0  ((uint32_t)(PMU_REG_BASE+0x0234))
#define PMU_DIG_DEG_CFG_VFEM_1  ((uint32_t)(PMU_REG_BASE+0x0238))
#define PMU_DIG_DEG_CFG_VSIM_0  ((uint32_t)(PMU_REG_BASE+0x023C))
#define PMU_DIG_DEG_CFG_VSIM_1  ((uint32_t)(PMU_REG_BASE+0x0240))
#define PMU_REG_BASE_CON0       ((uint32_t)(PMU_REG_BASE+0x0400))
#define PMU_REG_BASE_CON1       ((uint32_t)(PMU_REG_BASE+0x0404))
#define PMU_REG_BASE_CON2       ((uint32_t)(PMU_REG_BASE+0x0408))
#define PMU_REG_BASE_CON3       ((uint32_t)(PMU_REG_BASE+0x040C))
#define PMU_REG_BASE_CON4       ((uint32_t)(PMU_REG_BASE+0x0410))
#define PMU_REG_BASE_CON5       ((uint32_t)(PMU_REG_BASE+0x0414))
#define PMU_DIG_VRF_CON0        ((uint32_t)(PMU_REG_BASE+0x0600))
#define PMU_DIG_VCORE_CON0      ((uint32_t)(PMU_REG_BASE+0x0604))
#define PMU_DIG_VCORE_CON1      ((uint32_t)(PMU_REG_BASE+0x0608))
#define PMU_DIG_VCORE_CON2      ((uint32_t)(PMU_REG_BASE+0x060C))
#define PMU_DIG_VCORE_CON3      ((uint32_t)(PMU_REG_BASE+0x0610))
#define PMU_DIG_VCORE_CON4      ((uint32_t)(PMU_REG_BASE+0x0614))
#define PMU_DIG_VPA_CON0        ((uint32_t)(PMU_REG_BASE+0x0618))
#define PMU_DIG_VPA_CON1        ((uint32_t)(PMU_REG_BASE+0x061C))
#define PMU_DIG_VPA_CON2        ((uint32_t)(PMU_REG_BASE+0x0620))
#define PMU_DIG_VPA_CON3        ((uint32_t)(PMU_REG_BASE+0x0624))
#define PMU_DIG_VPA_CON4        ((uint32_t)(PMU_REG_BASE+0x0628))
#define PMU_DIG_VPA_CON5        ((uint32_t)(PMU_REG_BASE+0x062C))
#define PMU_DIG_VPA_CON7        ((uint32_t)(PMU_REG_BASE+0x0630))
#define PMU_DIG_VPA_CON8        ((uint32_t)(PMU_REG_BASE+0x0634))
#define PMU_DIG_VPA_CON9        ((uint32_t)(PMU_REG_BASE+0x0638))
#define PMU_DIG_VPA_CON10       ((uint32_t)(PMU_REG_BASE+0x063C))
#define PMU_DIG_VPA_CON11       ((uint32_t)(PMU_REG_BASE+0x0640))
#define PMU_DIG_VPA_CON12       ((uint32_t)(PMU_REG_BASE+0x0644))
#define PMU_DIG_VPA_CON13       ((uint32_t)(PMU_REG_BASE+0x0648))
#define PMU_DIG_VPA_CON14       ((uint32_t)(PMU_REG_BASE+0x064C))
#define PMU_DIG_VPA_CON15       ((uint32_t)(PMU_REG_BASE+0x0650))
#define PMU_DIG_VPA_CON16       ((uint32_t)(PMU_REG_BASE+0x0654))
#define PMU_DIG_VPA_CON17       ((uint32_t)(PMU_REG_BASE+0x0658))
#define PMU_DIG_VPA_CON18       ((uint32_t)(PMU_REG_BASE+0x065C))
#define PMU_DIG_VPA_CON19       ((uint32_t)(PMU_REG_BASE+0x0660))
#define PMU_DIG_VPA_CON20       ((uint32_t)(PMU_REG_BASE+0x0664))
#define PMU_DIG_VPA_CON21       ((uint32_t)(PMU_REG_BASE+0x0668))
#define PMU_DIG_VPA_CON22       ((uint32_t)(PMU_REG_BASE+0x066C))
#define PMU_DIG_VIO18_CON0      ((uint32_t)(PMU_REG_BASE+0x0800))
#define PMU_DIG_VIO18_CON1      ((uint32_t)(PMU_REG_BASE+0x0804))
#define PMU_DIG_VSIM_CON0       ((uint32_t)(PMU_REG_BASE+0x0808))
#define PMU_DIG_SRAM_CON0       ((uint32_t)(PMU_REG_BASE+0x080C))
#define PMU_DIG_SRAM_CON1       ((uint32_t)(PMU_REG_BASE+0x0810))
#define PMU_DIG_SRAM_CON2       ((uint32_t)(PMU_REG_BASE+0x0814))
#define PMU_DIG_SRAM_CON3       ((uint32_t)(PMU_REG_BASE+0x0818))
#define PMU_DIG_SRAM_CON4       ((uint32_t)(PMU_REG_BASE+0x081C))
#define DIG_VCORE_ANA_CON0      ((uint32_t)(PMU_REG_BASE+0x0A00))
#define DIG_VCORE_ANA_CON1      ((uint32_t)(PMU_REG_BASE+0x0A04))
#define DIG_VCORE_ANA_CON2      ((uint32_t)(PMU_REG_BASE+0x0A08))
#define DIG_VCORE_ANA_CON3      ((uint32_t)(PMU_REG_BASE+0x0A0C))
#define DIG_VCORE_ANA_CON4      ((uint32_t)(PMU_REG_BASE+0x0A10))
#define DIG_VCORE_ANA_CON5      ((uint32_t)(PMU_REG_BASE+0x0A14))
#define DIG_VCORE_ANA_CON6      ((uint32_t)(PMU_REG_BASE+0x0A18))
#define DIG_VCORE_ANA_CON7      ((uint32_t)(PMU_REG_BASE+0x0A1C))
#define DIG_VCORE_ANA_CON8      ((uint32_t)(PMU_REG_BASE+0x0A20))
#define DIG_VCORE_ANA_CON9      ((uint32_t)(PMU_REG_BASE+0x0A24))
#define DIG_VCORE_ANA_CON10     ((uint32_t)(PMU_REG_BASE+0x0A28))
#define DIG_VCORE_ANA_CON11     ((uint32_t)(PMU_REG_BASE+0x0A2C))
#define DIG_VCORE_ANA_CON12     ((uint32_t)(PMU_REG_BASE+0x0A30))
#define DIG_VCORE_ANA_CON13     ((uint32_t)(PMU_REG_BASE+0x0A34))
#define DIG_VCORE_ANA_CON14     ((uint32_t)(PMU_REG_BASE+0x0A38))
#define DIG_VCORE_ANA_CON15     ((uint32_t)(PMU_REG_BASE+0x0A3C))
#define DIG_VCORE_ANA_CON16     ((uint32_t)(PMU_REG_BASE+0x0A40))
#define DIG_VCORE_ANA_CON17     ((uint32_t)(PMU_REG_BASE+0x0A44))
#define DIG_VCORE_ANA_CON18     ((uint32_t)(PMU_REG_BASE+0x0A48))
#define DIG_VCORE_ANA_CON19     ((uint32_t)(PMU_REG_BASE+0x0A4C))
#define DIG_VCORE_ANA_CON20     ((uint32_t)(PMU_REG_BASE+0x0A50))
#define DIG_VCORE_ANA_CON21     ((uint32_t)(PMU_REG_BASE+0x0A54))
#define DIG_VCORE_ANA_CON22     ((uint32_t)(PMU_REG_BASE+0x0A58))
#define DIG_VCORE_ANA_CON23     ((uint32_t)(PMU_REG_BASE+0x0A5C))
#define DIG_VCORE_ANA_CON24     ((uint32_t)(PMU_REG_BASE+0x0A60))
#define DIG_VCORE_ANA_CON25     ((uint32_t)(PMU_REG_BASE+0x0A64))
#define DIG_VCORE_ANA_CON26     ((uint32_t)(PMU_REG_BASE+0x0A68))
#define DIG_VCORE_ANA_CON27     ((uint32_t)(PMU_REG_BASE+0x0A6C))
#define DIG_VCORE_ANA_CON28     ((uint32_t)(PMU_REG_BASE+0x0A70))
#define DIG_VCORE_ANA_CON29     ((uint32_t)(PMU_REG_BASE+0x0A74))
#define DIG_VCORE_ANA_CON30     ((uint32_t)(PMU_REG_BASE+0x0A78))
#define DIG_VCORE_ANA_CON31     ((uint32_t)(PMU_REG_BASE+0x0A7C))
#define DIG_VCORE_ANA_CON32     ((uint32_t)(PMU_REG_BASE+0x0A80))
#define DIG_VCORE_ANA_CON33     ((uint32_t)(PMU_REG_BASE+0x0A84))
#define DIG_VCORE_ANA_CON34     ((uint32_t)(PMU_REG_BASE+0x0A88))
#define DIG_VCORE_ANA_CON35     ((uint32_t)(PMU_REG_BASE+0x0A8C))
#define DIG_VCORE_ANA_CON36     ((uint32_t)(PMU_REG_BASE+0x0A90))
#define DIG_VCORE_ANA_CON37     ((uint32_t)(PMU_REG_BASE+0x0A94))
#define DIG_VCORE_ANA_CON38     ((uint32_t)(PMU_REG_BASE+0x0A98))
#define DIG_VCORE_ANA_CON39     ((uint32_t)(PMU_REG_BASE+0x0A9C))
//mask is HEX;  shift is Integer
#define PMU_RG_DIG_TOP_RSV0_ADDR                PMU_DIG_TOP_CON0
#define PMU_RG_DIG_TOP_RSV0_MASK                0xFFFF
#define PMU_RG_DIG_TOP_RSV0_SHIFT               0
#define PMU_RG_DIG_TOP_RSV1_ADDR                PMU_DIG_TOP_CON1
#define PMU_RG_DIG_TOP_RSV1_MASK                0xFFFF
#define PMU_RG_DIG_TOP_RSV1_SHIFT               0
#define PMU_RG_AD_GO_DSLP_ADDR                  PMU_DIG_TOP_CON2
#define PMU_RG_AD_GO_DSLP_MASK                  0x1
#define PMU_RG_AD_GO_DSLP_SHIFT                 0
#define PMU_RG_AD_GO_DSLP_SW_SEL_ADDR           PMU_DIG_TOP_CON2
#define PMU_RG_AD_GO_DSLP_SW_SEL_MASK           0x1
#define PMU_RG_AD_GO_DSLP_SW_SEL_SHIFT          1
#define PMU_RG_AD_BGR_SEL_ADDR                  PMU_DIG_TOP_CON2
#define PMU_RG_AD_BGR_SEL_MASK                  0x1
#define PMU_RG_AD_BGR_SEL_SHIFT                 2
#define PMU_RG_AD_BGR_SEL_SW_SEL_ADDR           PMU_DIG_TOP_CON2
#define PMU_RG_AD_BGR_SEL_SW_SEL_MASK           0x1
#define PMU_RG_AD_BGR_SEL_SW_SEL_SHIFT          3
#define PMU_RG_TESTMODE_DVS_EN_ADDR             PMU_DIG_TOP_CON2
#define PMU_RG_TESTMODE_DVS_EN_MASK             0x1
#define PMU_RG_TESTMODE_DVS_EN_SHIFT            4
#define PMU_RG_VCORE_FORCE_NORMAL_ADDR          PMU_DIG_TOP_CON2
#define PMU_RG_VCORE_FORCE_NORMAL_MASK          0x1
#define PMU_RG_VCORE_FORCE_NORMAL_SHIFT         5
#define PMU_RG_TOP_MON_GRP_SEL_ADDR             PMU_DIG_TOP_TEST_CON0
#define PMU_RG_TOP_MON_GRP_SEL_MASK             0x3F
#define PMU_RG_TOP_MON_GRP_SEL_SHIFT            0
#define PMU_RG_TOP_TEST_OUT_ADDR                PMU_DIG_TOP_TEST_CON0
#define PMU_RG_TOP_TEST_OUT_MASK                0xFF
#define PMU_RG_TOP_TEST_OUT_SHIFT               8
#define PMU_RGS_AD_VCORE_DIG_MON_ADDR           PMU_DIG_TOP_MON0
#define PMU_RGS_AD_VCORE_DIG_MON_MASK           0xF
#define PMU_RGS_AD_VCORE_DIG_MON_SHIFT          0
#define PMU_RGS_AD_VCORE_POWER_GOOD_VCORE_ADDR  PMU_DIG_TOP_MON1
#define PMU_RGS_AD_VCORE_POWER_GOOD_VCORE_MASK  0x1
#define PMU_RGS_AD_VCORE_POWER_GOOD_VCORE_SHIFT 0
#define PMU_RGS_AD_VRF_DIG_MON_ADDR             PMU_DIG_TOP_MON1
#define PMU_RGS_AD_VRF_DIG_MON_MASK             0xF
#define PMU_RGS_AD_VRF_DIG_MON_SHIFT            1
#define PMU_RGS_AD_VFEM_OCEN_STATUS_ADDR        PMU_DIG_TOP_MON2
#define PMU_RGS_AD_VFEM_OCEN_STATUS_MASK        0x1
#define PMU_RGS_AD_VFEM_OCEN_STATUS_SHIFT       0
#define PMU_RGS_AD_VFEM_PG_STATUS_ADDR          PMU_DIG_TOP_MON2
#define PMU_RGS_AD_VFEM_PG_STATUS_MASK          0x1
#define PMU_RGS_AD_VFEM_PG_STATUS_SHIFT         1
#define PMU_RGS_AD_VFEM_OC_STATUS_ADDR          PMU_DIG_TOP_MON2
#define PMU_RGS_AD_VFEM_OC_STATUS_MASK          0x1
#define PMU_RGS_AD_VFEM_OC_STATUS_SHIFT         2
#define PMU_RGS_AD_VIO18_OCEN_STATUS_ADDR       PMU_DIG_TOP_MON3
#define PMU_RGS_AD_VIO18_OCEN_STATUS_MASK       0x1
#define PMU_RGS_AD_VIO18_OCEN_STATUS_SHIFT      0
#define PMU_RGS_AD_VIO18_PG_STATUS_ADDR         PMU_DIG_TOP_MON3
#define PMU_RGS_AD_VIO18_PG_STATUS_MASK         0x1
#define PMU_RGS_AD_VIO18_PG_STATUS_SHIFT        1
#define PMU_RGS_AD_VIO18_OC_STATUS_ADDR         PMU_DIG_TOP_MON3
#define PMU_RGS_AD_VIO18_OC_STATUS_MASK         0x1
#define PMU_RGS_AD_VIO18_OC_STATUS_SHIFT        2
#define PMU_RGS_AD_VSIM_OCEN_STATUS_ADDR        PMU_DIG_TOP_MON4
#define PMU_RGS_AD_VSIM_OCEN_STATUS_MASK        0x1
#define PMU_RGS_AD_VSIM_OCEN_STATUS_SHIFT       0
#define PMU_RGS_AD_VSIM_PG_STATUS_ADDR          PMU_DIG_TOP_MON4
#define PMU_RGS_AD_VSIM_PG_STATUS_MASK          0x1
#define PMU_RGS_AD_VSIM_PG_STATUS_SHIFT         1
#define PMU_RGS_AD_VSIM_OC_STATUS_ADDR          PMU_DIG_TOP_MON4
#define PMU_RGS_AD_VSIM_OC_STATUS_MASK          0x1
#define PMU_RGS_AD_VSIM_OC_STATUS_SHIFT         2
#define PMU_RGS_AD_VSRAM_OCEN_STATUS_ADDR       PMU_DIG_TOP_MON5
#define PMU_RGS_AD_VSRAM_OCEN_STATUS_MASK       0x1
#define PMU_RGS_AD_VSRAM_OCEN_STATUS_SHIFT      0
#define PMU_RGS_AD_VSRAM_PG_STATUS_ADDR         PMU_DIG_TOP_MON5
#define PMU_RGS_AD_VSRAM_PG_STATUS_MASK         0x1
#define PMU_RGS_AD_VSRAM_PG_STATUS_SHIFT        1
#define PMU_RGS_AD_VSRAM_OC_STATUS_ADDR         PMU_DIG_TOP_MON5
#define PMU_RGS_AD_VSRAM_OC_STATUS_MASK         0x1
#define PMU_RGS_AD_VSRAM_OC_STATUS_SHIFT        2
#define PMU_RGS_STRUP_DEBUG_OUT_ADDR            PMU_DIG_TOP_MON6
#define PMU_RGS_STRUP_DEBUG_OUT_MASK            0xFF
#define PMU_RGS_STRUP_DEBUG_OUT_SHIFT           0
#define PMU_RGS_AD_ANA_DEBUG_OUT0_ADDR          PMU_DIG_TOP_MON7
#define PMU_RGS_AD_ANA_DEBUG_OUT0_MASK          0xFF
#define PMU_RGS_AD_ANA_DEBUG_OUT0_SHIFT         0
#define PMU_RGS_AD_ANA_DEBUG_OUT1_ADDR          PMU_DIG_TOP_MON8
#define PMU_RGS_AD_ANA_DEBUG_OUT1_MASK          0xFF
#define PMU_RGS_AD_ANA_DEBUG_OUT1_SHIFT         0
#define PMU_RGS_AD_ANA_DEBUG_OUT2_ADDR          PMU_DIG_TOP_MON9
#define PMU_RGS_AD_ANA_DEBUG_OUT2_MASK          0xFF
#define PMU_RGS_AD_ANA_DEBUG_OUT2_SHIFT         0
#define PMU_RGS_AD_VPA_DIG_MON_ADDR             PMU_DIG_TOP_MON10
#define PMU_RGS_AD_VPA_DIG_MON_MASK             0x7
#define PMU_RGS_AD_VPA_DIG_MON_SHIFT            0
#define PMU_RGS_DA_VRF_SS_ADDR                  PMU_DIG_TOP_MON11
#define PMU_RGS_DA_VRF_SS_MASK                  0x1
#define PMU_RGS_DA_VRF_SS_SHIFT                 0
#define PMU_RGS_DA_VRF_EN_ADDR                  PMU_DIG_TOP_MON11
#define PMU_RGS_DA_VRF_EN_MASK                  0x1
#define PMU_RGS_DA_VRF_EN_SHIFT                 1
#define PMU_RGS_DAD_VIO18_EN_ADDR               PMU_DIG_TOP_MON11
#define PMU_RGS_DAD_VIO18_EN_MASK               0x1
#define PMU_RGS_DAD_VIO18_EN_SHIFT              2
#define PMU_RGS_DAD_VCORE_SS_ADDR               PMU_DIG_TOP_MON11
#define PMU_RGS_DAD_VCORE_SS_MASK               0x1
#define PMU_RGS_DAD_VCORE_SS_SHIFT              3
#define PMU_RGS_DAD_VCORE_EN_ADDR               PMU_DIG_TOP_MON11
#define PMU_RGS_DAD_VCORE_EN_MASK               0x1
#define PMU_RGS_DAD_VCORE_EN_SHIFT              4
#define PMU_RGS_DA_DIG_LSLP_STAT_ADDR           PMU_DIG_TOP_MON11
#define PMU_RGS_DA_DIG_LSLP_STAT_MASK           0x1
#define PMU_RGS_DA_DIG_LSLP_STAT_SHIFT          5
#define PMU_RGS_VCORE_POWER_STATE_ADDR          PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_POWER_STATE_MASK          0xF
#define PMU_RGS_VCORE_POWER_STATE_SHIFT         0
#define PMU_RGS_VCORE_LSLP_ENTRY_ADDR           PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_LSLP_ENTRY_MASK           0x1
#define PMU_RGS_VCORE_LSLP_ENTRY_SHIFT          4
#define PMU_RGS_VCORE_LSLP_EXIT_ADDR            PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_LSLP_EXIT_MASK            0x1
#define PMU_RGS_VCORE_LSLP_EXIT_SHIFT           5
#define PMU_RGS_VCORE_DSLP_ENTRY_ADDR           PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_DSLP_ENTRY_MASK           0x1
#define PMU_RGS_VCORE_DSLP_ENTRY_SHIFT          6
#define PMU_RGS_VCORE_GO_LSLP_ADDR              PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_GO_LSLP_MASK              0x1
#define PMU_RGS_VCORE_GO_LSLP_SHIFT             7
#define PMU_RGS_VCORE_GO_LSLP_SOURCE_ADDR       PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_GO_LSLP_SOURCE_MASK       0x1
#define PMU_RGS_VCORE_GO_LSLP_SOURCE_SHIFT      8
#define PMU_RGS_VCORE_GO_DSLP_ADDR              PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_GO_DSLP_MASK              0x1
#define PMU_RGS_VCORE_GO_DSLP_SHIFT             9
#define PMU_RGS_VCORE_GO_DSLP_SOURCE_ADDR       PMU_DIG_TOP_MON12
#define PMU_RGS_VCORE_GO_DSLP_SOURCE_MASK       0x1
#define PMU_RGS_VCORE_GO_DSLP_SOURCE_SHIFT      10
#define PMU_RGS_DA_VCORE_VOSEL_ADDR             PMU_DIG_TOP_MON13
#define PMU_RGS_DA_VCORE_VOSEL_MASK             0x1F
#define PMU_RGS_DA_VCORE_VOSEL_SHIFT            0
#define PMU_RGS_VCORE_VOSEL_TARGET_ADDR         PMU_DIG_TOP_MON13
#define PMU_RGS_VCORE_VOSEL_TARGET_MASK         0x1F
#define PMU_RGS_VCORE_VOSEL_TARGET_SHIFT        5
#define PMU_RGS_DA_VSRAM_VOSEL_ADDR             PMU_DIG_TOP_MON14
#define PMU_RGS_DA_VSRAM_VOSEL_MASK             0x1F
#define PMU_RGS_DA_VSRAM_VOSEL_SHIFT            0
#define PMU_RGS_VSRAM_VOSEL_TARGET_ADDR         PMU_DIG_TOP_MON14
#define PMU_RGS_VSRAM_VOSEL_TARGET_MASK         0x1F
#define PMU_RGS_VSRAM_VOSEL_TARGET_SHIFT        5
#define PMU_RGS_AD_VSRAM_VOSEL_ADDR             PMU_DIG_TOP_MON14
#define PMU_RGS_AD_VSRAM_VOSEL_MASK             0x1F
#define PMU_RGS_AD_VSRAM_VOSEL_SHIFT            10
#define PMU_RGS_AD_VSRAM_VOSEL_DSLP_ADDR        PMU_DIG_TOP_MON14
#define PMU_RGS_AD_VSRAM_VOSEL_DSLP_MASK        0x1
#define PMU_RGS_AD_VSRAM_VOSEL_DSLP_SHIFT       15
#define PMU_RG_PMU_DIG_INT_POLARITY_ADDR        PMU_DIG_INT_MISC
#define PMU_RG_PMU_DIG_INT_POLARITY_MASK        0x1
#define PMU_RG_PMU_DIG_INT_POLARITY_SHIFT       0
#define PMU_RG_INT_STATUS_PG_VCORE_ADDR         PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_PG_VCORE_MASK         0x1
#define PMU_RG_INT_STATUS_PG_VCORE_SHIFT        0
#define PMU_RG_INT_STATUS_PG_VRF_ADDR           PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_PG_VRF_MASK           0x1
#define PMU_RG_INT_STATUS_PG_VRF_SHIFT          1
#define PMU_RG_INT_STATUS_OC_VPA_ADDR           PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_OC_VPA_MASK           0x1
#define PMU_RG_INT_STATUS_OC_VPA_SHIFT          2
#define PMU_RG_INT_STATUS_PG_VIO18_ADDR         PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_PG_VIO18_MASK         0x1
#define PMU_RG_INT_STATUS_PG_VIO18_SHIFT        3
#define PMU_RG_INT_STATUS_OC_VIO18_ADDR         PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_OC_VIO18_MASK         0x1
#define PMU_RG_INT_STATUS_OC_VIO18_SHIFT        4
#define PMU_RG_INT_STATUS_PG_VSRAM_ADDR         PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_PG_VSRAM_MASK         0x1
#define PMU_RG_INT_STATUS_PG_VSRAM_SHIFT        5
#define PMU_RG_INT_STATUS_OC_VSRAM_ADDR         PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_OC_VSRAM_MASK         0x1
#define PMU_RG_INT_STATUS_OC_VSRAM_SHIFT        6
#define PMU_RG_INT_STATUS_PG_VFEM_ADDR          PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_PG_VFEM_MASK          0x1
#define PMU_RG_INT_STATUS_PG_VFEM_SHIFT         7
#define PMU_RG_INT_STATUS_OC_VFEM_ADDR          PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_OC_VFEM_MASK          0x1
#define PMU_RG_INT_STATUS_OC_VFEM_SHIFT         8
#define PMU_RG_INT_STATUS_PG_VSIM_ADDR          PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_PG_VSIM_MASK          0x1
#define PMU_RG_INT_STATUS_PG_VSIM_SHIFT         9
#define PMU_RG_INT_STATUS_OC_VSIM_ADDR          PMU_DIG_INT_STATUS
#define PMU_RG_INT_STATUS_OC_VSIM_MASK          0x1
#define PMU_RG_INT_STATUS_OC_VSIM_SHIFT         10
#define PMU_RG_INT_RAW_STATUS_PG_VCORE_ADDR     PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_PG_VCORE_MASK     0x1
#define PMU_RG_INT_RAW_STATUS_PG_VCORE_SHIFT    0
#define PMU_RG_INT_RAW_STATUS_PG_VRF_ADDR       PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_PG_VRF_MASK       0x1
#define PMU_RG_INT_RAW_STATUS_PG_VRF_SHIFT      1
#define PMU_RG_INT_RAW_STATUS_OC_VPA_ADDR       PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_OC_VPA_MASK       0x1
#define PMU_RG_INT_RAW_STATUS_OC_VPA_SHIFT      2
#define PMU_RG_INT_RAW_STATUS_PG_VIO18_ADDR     PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_PG_VIO18_MASK     0x1
#define PMU_RG_INT_RAW_STATUS_PG_VIO18_SHIFT    3
#define PMU_RG_INT_RAW_STATUS_OC_VIO18_ADDR     PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_OC_VIO18_MASK     0x1
#define PMU_RG_INT_RAW_STATUS_OC_VIO18_SHIFT    4
#define PMU_RG_INT_RAW_STATUS_PG_VSRAM_ADDR     PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_PG_VSRAM_MASK     0x1
#define PMU_RG_INT_RAW_STATUS_PG_VSRAM_SHIFT    5
#define PMU_RG_INT_RAW_STATUS_OC_VSRAM_ADDR     PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_OC_VSRAM_MASK     0x1
#define PMU_RG_INT_RAW_STATUS_OC_VSRAM_SHIFT    6
#define PMU_RG_INT_RAW_STATUS_PG_VFEM_ADDR      PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_PG_VFEM_MASK      0x1
#define PMU_RG_INT_RAW_STATUS_PG_VFEM_SHIFT     7
#define PMU_RG_INT_RAW_STATUS_OC_VFEM_ADDR      PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_OC_VFEM_MASK      0x1
#define PMU_RG_INT_RAW_STATUS_OC_VFEM_SHIFT     8
#define PMU_RG_INT_RAW_STATUS_PG_VSIM_ADDR      PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_PG_VSIM_MASK      0x1
#define PMU_RG_INT_RAW_STATUS_PG_VSIM_SHIFT     9
#define PMU_RG_INT_RAW_STATUS_OC_VSIM_ADDR      PMU_DIG_INT_RAW_STATUS
#define PMU_RG_INT_RAW_STATUS_OC_VSIM_MASK      0x1
#define PMU_RG_INT_RAW_STATUS_OC_VSIM_SHIFT     10
#define PMU_RG_INT_STATUS_CLR_PG_VCORE_ADDR     PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_PG_VCORE_MASK     0x1
#define PMU_RG_INT_STATUS_CLR_PG_VCORE_SHIFT    0
#define PMU_RG_INT_STATUS_CLR_PG_VRF_ADDR       PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_PG_VRF_MASK       0x1
#define PMU_RG_INT_STATUS_CLR_PG_VRF_SHIFT      1
#define PMU_RG_INT_STATUS_CLR_OC_VPA_ADDR       PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_OC_VPA_MASK       0x1
#define PMU_RG_INT_STATUS_CLR_OC_VPA_SHIFT      2
#define PMU_RG_INT_STATUS_CLR_PG_VIO18_ADDR     PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_PG_VIO18_MASK     0x1
#define PMU_RG_INT_STATUS_CLR_PG_VIO18_SHIFT    3
#define PMU_RG_INT_STATUS_CLR_OC_VIO18_ADDR     PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_OC_VIO18_MASK     0x1
#define PMU_RG_INT_STATUS_CLR_OC_VIO18_SHIFT    4
#define PMU_RG_INT_STATUS_CLR_PG_VSRAM_ADDR     PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_PG_VSRAM_MASK     0x1
#define PMU_RG_INT_STATUS_CLR_PG_VSRAM_SHIFT    5
#define PMU_RG_INT_STATUS_CLR_OC_VSRAM_ADDR     PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_OC_VSRAM_MASK     0x1
#define PMU_RG_INT_STATUS_CLR_OC_VSRAM_SHIFT    6
#define PMU_RG_INT_STATUS_CLR_PG_VFEM_ADDR      PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_PG_VFEM_MASK      0x1
#define PMU_RG_INT_STATUS_CLR_PG_VFEM_SHIFT     7
#define PMU_RG_INT_STATUS_CLR_OC_VFEM_ADDR      PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_OC_VFEM_MASK      0x1
#define PMU_RG_INT_STATUS_CLR_OC_VFEM_SHIFT     8
#define PMU_RG_INT_STATUS_CLR_PG_VSIM_ADDR      PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_PG_VSIM_MASK      0x1
#define PMU_RG_INT_STATUS_CLR_PG_VSIM_SHIFT     9
#define PMU_RG_INT_STATUS_CLR_OC_VSIM_ADDR      PMU_DIG_INT_STATUS_CLR
#define PMU_RG_INT_STATUS_CLR_OC_VSIM_MASK      0x1
#define PMU_RG_INT_STATUS_CLR_OC_VSIM_SHIFT     10
#define PMU_RG_INT_EN_PG_VCORE_ADDR             PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_PG_VCORE_MASK             0x1
#define PMU_RG_INT_EN_PG_VCORE_SHIFT            0
#define PMU_RG_INT_EN_PG_VRF_ADDR               PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_PG_VRF_MASK               0x1
#define PMU_RG_INT_EN_PG_VRF_SHIFT              1
#define PMU_RG_INT_EN_OC_VPA_ADDR               PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_OC_VPA_MASK               0x1
#define PMU_RG_INT_EN_OC_VPA_SHIFT              2
#define PMU_RG_INT_EN_PG_VIO18_ADDR             PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_PG_VIO18_MASK             0x1
#define PMU_RG_INT_EN_PG_VIO18_SHIFT            3
#define PMU_RG_INT_EN_OC_VIO18_ADDR             PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_OC_VIO18_MASK             0x1
#define PMU_RG_INT_EN_OC_VIO18_SHIFT            4
#define PMU_RG_INT_EN_PG_VSRAM_ADDR             PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_PG_VSRAM_MASK             0x1
#define PMU_RG_INT_EN_PG_VSRAM_SHIFT            5
#define PMU_RG_INT_EN_OC_VSRAM_ADDR             PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_OC_VSRAM_MASK             0x1
#define PMU_RG_INT_EN_OC_VSRAM_SHIFT            6
#define PMU_RG_INT_EN_PG_VFEM_ADDR              PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_PG_VFEM_MASK              0x1
#define PMU_RG_INT_EN_PG_VFEM_SHIFT             7
#define PMU_RG_INT_EN_OC_VFEM_ADDR              PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_OC_VFEM_MASK              0x1
#define PMU_RG_INT_EN_OC_VFEM_SHIFT             8
#define PMU_RG_INT_EN_PG_VSIM_ADDR              PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_PG_VSIM_MASK              0x1
#define PMU_RG_INT_EN_PG_VSIM_SHIFT             9
#define PMU_RG_INT_EN_OC_VSIM_ADDR              PMU_DIG_INT_EN_CON
#define PMU_RG_INT_EN_OC_VSIM_MASK              0x1
#define PMU_RG_INT_EN_OC_VSIM_SHIFT             10
#define PMU_RG_INT_MASK_PG_VCORE_ADDR           PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_PG_VCORE_MASK           0x1
#define PMU_RG_INT_MASK_PG_VCORE_SHIFT          0
#define PMU_RG_INT_MASK_PG_VRF_ADDR             PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_PG_VRF_MASK             0x1
#define PMU_RG_INT_MASK_PG_VRF_SHIFT            1
#define PMU_RG_INT_MASK_OC_VPA_ADDR             PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_OC_VPA_MASK             0x1
#define PMU_RG_INT_MASK_OC_VPA_SHIFT            2
#define PMU_RG_INT_MASK_PG_VIO18_ADDR           PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_PG_VIO18_MASK           0x1
#define PMU_RG_INT_MASK_PG_VIO18_SHIFT          3
#define PMU_RG_INT_MASK_OC_VIO18_ADDR           PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_OC_VIO18_MASK           0x1
#define PMU_RG_INT_MASK_OC_VIO18_SHIFT          4
#define PMU_RG_INT_MASK_PG_VSRAM_ADDR           PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_PG_VSRAM_MASK           0x1
#define PMU_RG_INT_MASK_PG_VSRAM_SHIFT          5
#define PMU_RG_INT_MASK_OC_VSRAM_ADDR           PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_OC_VSRAM_MASK           0x1
#define PMU_RG_INT_MASK_OC_VSRAM_SHIFT          6
#define PMU_RG_INT_MASK_PG_VFEM_ADDR            PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_PG_VFEM_MASK            0x1
#define PMU_RG_INT_MASK_PG_VFEM_SHIFT           7
#define PMU_RG_INT_MASK_OC_VFEM_ADDR            PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_OC_VFEM_MASK            0x1
#define PMU_RG_INT_MASK_OC_VFEM_SHIFT           8
#define PMU_RG_INT_MASK_PG_VSIM_ADDR            PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_PG_VSIM_MASK            0x1
#define PMU_RG_INT_MASK_PG_VSIM_SHIFT           9
#define PMU_RG_INT_MASK_OC_VSIM_ADDR            PMU_DIG_INT_MASK_CON
#define PMU_RG_INT_MASK_OC_VSIM_MASK            0x1
#define PMU_RG_INT_MASK_OC_VSIM_SHIFT           10
#define PMU_RG_DEG_EN_PG_VCORE_ADDR             PMU_DIG_DEG_CFG_VCORE
#define PMU_RG_DEG_EN_PG_VCORE_MASK             0x1
#define PMU_RG_DEG_EN_PG_VCORE_SHIFT            0
#define PMU_RG_DEG_WND_PG_VCORE_ADDR            PMU_DIG_DEG_CFG_VCORE
#define PMU_RG_DEG_WND_PG_VCORE_MASK            0x1
#define PMU_RG_DEG_WND_PG_VCORE_SHIFT           1
#define PMU_RG_DEG_THD_PG_VCORE_ADDR            PMU_DIG_DEG_CFG_VCORE
#define PMU_RG_DEG_THD_PG_VCORE_MASK            0x3
#define PMU_RG_DEG_THD_PG_VCORE_SHIFT           3
#define PMU_RG_DEG_IN_PG_VCORE_ADDR             PMU_DIG_DEG_CFG_VCORE
#define PMU_RG_DEG_IN_PG_VCORE_MASK             0x1
#define PMU_RG_DEG_IN_PG_VCORE_SHIFT            5
#define PMU_RG_DEG_OUT_PG_VCORE_ADDR            PMU_DIG_DEG_CFG_VCORE
#define PMU_RG_DEG_OUT_PG_VCORE_MASK            0x1
#define PMU_RG_DEG_OUT_PG_VCORE_SHIFT           6
#define PMU_RG_DEG_EN_PG_VRF_ADDR               PMU_DIG_DEG_CFG_VRF
#define PMU_RG_DEG_EN_PG_VRF_MASK               0x1
#define PMU_RG_DEG_EN_PG_VRF_SHIFT              0
#define PMU_RG_DEG_WND_PG_VRF_ADDR              PMU_DIG_DEG_CFG_VRF
#define PMU_RG_DEG_WND_PG_VRF_MASK              0x1
#define PMU_RG_DEG_WND_PG_VRF_SHIFT             1
#define PMU_RG_DEG_THD_PG_VRF_ADDR              PMU_DIG_DEG_CFG_VRF
#define PMU_RG_DEG_THD_PG_VRF_MASK              0x3
#define PMU_RG_DEG_THD_PG_VRF_SHIFT             3
#define PMU_RG_DEG_IN_PG_VRF_ADDR               PMU_DIG_DEG_CFG_VRF
#define PMU_RG_DEG_IN_PG_VRF_MASK               0x1
#define PMU_RG_DEG_IN_PG_VRF_SHIFT              5
#define PMU_RG_DEG_OUT_PG_VRF_ADDR              PMU_DIG_DEG_CFG_VRF
#define PMU_RG_DEG_OUT_PG_VRF_MASK              0x1
#define PMU_RG_DEG_OUT_PG_VRF_SHIFT             6
#define PMU_RG_DEG_EN_OC_VPA_ADDR               PMU_DIG_DEG_CFG_VPA
#define PMU_RG_DEG_EN_OC_VPA_MASK               0x1
#define PMU_RG_DEG_EN_OC_VPA_SHIFT              0
#define PMU_RG_DEG_WND_OC_VPA_ADDR              PMU_DIG_DEG_CFG_VPA
#define PMU_RG_DEG_WND_OC_VPA_MASK              0x3
#define PMU_RG_DEG_WND_OC_VPA_SHIFT             1
#define PMU_RG_DEG_THD_OC_VPA_ADDR              PMU_DIG_DEG_CFG_VPA
#define PMU_RG_DEG_THD_OC_VPA_MASK              0x3
#define PMU_RG_DEG_THD_OC_VPA_SHIFT             3
#define PMU_RG_DEG_IN_OC_VPA_ADDR               PMU_DIG_DEG_CFG_VPA
#define PMU_RG_DEG_IN_OC_VPA_MASK               0x1
#define PMU_RG_DEG_IN_OC_VPA_SHIFT              5
#define PMU_RG_DEG_OUT_OC_VPA_ADDR              PMU_DIG_DEG_CFG_VPA
#define PMU_RG_DEG_OUT_OC_VPA_MASK              0x1
#define PMU_RG_DEG_OUT_OC_VPA_SHIFT             6
#define PMU_RG_DEG_EN_PG_VIO18_ADDR             PMU_DIG_DEG_CFG_VIO18_0
#define PMU_RG_DEG_EN_PG_VIO18_MASK             0x1
#define PMU_RG_DEG_EN_PG_VIO18_SHIFT            0
#define PMU_RG_DEG_WND_PG_VIO18_ADDR            PMU_DIG_DEG_CFG_VIO18_0
#define PMU_RG_DEG_WND_PG_VIO18_MASK            0x1
#define PMU_RG_DEG_WND_PG_VIO18_SHIFT           1
#define PMU_RG_DEG_THD_PG_VIO18_ADDR            PMU_DIG_DEG_CFG_VIO18_0
#define PMU_RG_DEG_THD_PG_VIO18_MASK            0x3
#define PMU_RG_DEG_THD_PG_VIO18_SHIFT           3
#define PMU_RG_DEG_IN_PG_VIO18_ADDR             PMU_DIG_DEG_CFG_VIO18_0
#define PMU_RG_DEG_IN_PG_VIO18_MASK             0x1
#define PMU_RG_DEG_IN_PG_VIO18_SHIFT            5
#define PMU_RG_DEG_OUT_PG_VIO18_ADDR            PMU_DIG_DEG_CFG_VIO18_0
#define PMU_RG_DEG_OUT_PG_VIO18_MASK            0x1
#define PMU_RG_DEG_OUT_PG_VIO18_SHIFT           6
#define PMU_RG_DEG_EN_OC_VIO18_ADDR             PMU_DIG_DEG_CFG_VIO18_1
#define PMU_RG_DEG_EN_OC_VIO18_MASK             0x1
#define PMU_RG_DEG_EN_OC_VIO18_SHIFT            0
#define PMU_RG_DEG_WND_OC_VIO18_ADDR            PMU_DIG_DEG_CFG_VIO18_1
#define PMU_RG_DEG_WND_OC_VIO18_MASK            0x1
#define PMU_RG_DEG_WND_OC_VIO18_SHIFT           1
#define PMU_RG_DEG_THD_OC_VIO18_ADDR            PMU_DIG_DEG_CFG_VIO18_1
#define PMU_RG_DEG_THD_OC_VIO18_MASK            0x3
#define PMU_RG_DEG_THD_OC_VIO18_SHIFT           3
#define PMU_RG_DEG_IN_OC_VIO18_ADDR             PMU_DIG_DEG_CFG_VIO18_1
#define PMU_RG_DEG_IN_OC_VIO18_MASK             0x1
#define PMU_RG_DEG_IN_OC_VIO18_SHIFT            5
#define PMU_RG_DEG_OUT_OC_VIO18_ADDR            PMU_DIG_DEG_CFG_VIO18_1
#define PMU_RG_DEG_OUT_OC_VIO18_MASK            0x1
#define PMU_RG_DEG_OUT_OC_VIO18_SHIFT           6
#define PMU_RG_DEG_EN_PG_VSRAM_ADDR             PMU_DIG_DEG_CFG_VSRAM_0
#define PMU_RG_DEG_EN_PG_VSRAM_MASK             0x1
#define PMU_RG_DEG_EN_PG_VSRAM_SHIFT            0
#define PMU_RG_DEG_WND_PG_VSRAM_ADDR            PMU_DIG_DEG_CFG_VSRAM_0
#define PMU_RG_DEG_WND_PG_VSRAM_MASK            0x1
#define PMU_RG_DEG_WND_PG_VSRAM_SHIFT           1
#define PMU_RG_DEG_THD_PG_VSRAM_ADDR            PMU_DIG_DEG_CFG_VSRAM_0
#define PMU_RG_DEG_THD_PG_VSRAM_MASK            0x3
#define PMU_RG_DEG_THD_PG_VSRAM_SHIFT           3
#define PMU_RG_DEG_IN_PG_VSRAM_ADDR             PMU_DIG_DEG_CFG_VSRAM_0
#define PMU_RG_DEG_IN_PG_VSRAM_MASK             0x1
#define PMU_RG_DEG_IN_PG_VSRAM_SHIFT            5
#define PMU_RG_DEG_OUT_PG_VSRAM_ADDR            PMU_DIG_DEG_CFG_VSRAM_0
#define PMU_RG_DEG_OUT_PG_VSRAM_MASK            0x1
#define PMU_RG_DEG_OUT_PG_VSRAM_SHIFT           6
#define PMU_RG_DEG_EN_OC_VSRAM_ADDR             PMU_DIG_DEG_CFG_VSRAM_1
#define PMU_RG_DEG_EN_OC_VSRAM_MASK             0x1
#define PMU_RG_DEG_EN_OC_VSRAM_SHIFT            0
#define PMU_RG_DEG_WND_OC_VSRAM_ADDR            PMU_DIG_DEG_CFG_VSRAM_1
#define PMU_RG_DEG_WND_OC_VSRAM_MASK            0x1
#define PMU_RG_DEG_WND_OC_VSRAM_SHIFT           1
#define PMU_RG_DEG_THD_OC_VSRAM_ADDR            PMU_DIG_DEG_CFG_VSRAM_1
#define PMU_RG_DEG_THD_OC_VSRAM_MASK            0x3
#define PMU_RG_DEG_THD_OC_VSRAM_SHIFT           3
#define PMU_RG_DEG_IN_OC_VSRAM_ADDR             PMU_DIG_DEG_CFG_VSRAM_1
#define PMU_RG_DEG_IN_OC_VSRAM_MASK             0x1
#define PMU_RG_DEG_IN_OC_VSRAM_SHIFT            5
#define PMU_RG_DEG_OUT_OC_VSRAM_ADDR            PMU_DIG_DEG_CFG_VSRAM_1
#define PMU_RG_DEG_OUT_OC_VSRAM_MASK            0x1
#define PMU_RG_DEG_OUT_OC_VSRAM_SHIFT           6
#define PMU_RG_DEG_EN_PG_VFEM_ADDR              PMU_DIG_DEG_CFG_VFEM_0
#define PMU_RG_DEG_EN_PG_VFEM_MASK              0x1
#define PMU_RG_DEG_EN_PG_VFEM_SHIFT             0
#define PMU_RG_DEG_WND_PG_VFEM_ADDR             PMU_DIG_DEG_CFG_VFEM_0
#define PMU_RG_DEG_WND_PG_VFEM_MASK             0x1
#define PMU_RG_DEG_WND_PG_VFEM_SHIFT            1
#define PMU_RG_DEG_THD_PG_VFEM_ADDR             PMU_DIG_DEG_CFG_VFEM_0
#define PMU_RG_DEG_THD_PG_VFEM_MASK             0x3
#define PMU_RG_DEG_THD_PG_VFEM_SHIFT            3
#define PMU_RG_DEG_IN_PG_VFEM_ADDR              PMU_DIG_DEG_CFG_VFEM_0
#define PMU_RG_DEG_IN_PG_VFEM_MASK              0x1
#define PMU_RG_DEG_IN_PG_VFEM_SHIFT             5
#define PMU_RG_DEG_OUT_PG_VFEM_ADDR             PMU_DIG_DEG_CFG_VFEM_0
#define PMU_RG_DEG_OUT_PG_VFEM_MASK             0x1
#define PMU_RG_DEG_OUT_PG_VFEM_SHIFT            6
#define PMU_RG_DEG_EN_OC_VFEM_ADDR              PMU_DIG_DEG_CFG_VFEM_1
#define PMU_RG_DEG_EN_OC_VFEM_MASK              0x1
#define PMU_RG_DEG_EN_OC_VFEM_SHIFT             0
#define PMU_RG_DEG_WND_OC_VFEM_ADDR             PMU_DIG_DEG_CFG_VFEM_1
#define PMU_RG_DEG_WND_OC_VFEM_MASK             0x1
#define PMU_RG_DEG_WND_OC_VFEM_SHIFT            1
#define PMU_RG_DEG_THD_OC_VFEM_ADDR             PMU_DIG_DEG_CFG_VFEM_1
#define PMU_RG_DEG_THD_OC_VFEM_MASK             0x3
#define PMU_RG_DEG_THD_OC_VFEM_SHIFT            3
#define PMU_RG_DEG_IN_OC_VFEM_ADDR              PMU_DIG_DEG_CFG_VFEM_1
#define PMU_RG_DEG_IN_OC_VFEM_MASK              0x1
#define PMU_RG_DEG_IN_OC_VFEM_SHIFT             5
#define PMU_RG_DEG_OUT_OC_VFEM_ADDR             PMU_DIG_DEG_CFG_VFEM_1
#define PMU_RG_DEG_OUT_OC_VFEM_MASK             0x1
#define PMU_RG_DEG_OUT_OC_VFEM_SHIFT            6
#define PMU_RG_DEG_EN_PG_VSIM_ADDR              PMU_DIG_DEG_CFG_VSIM_0
#define PMU_RG_DEG_EN_PG_VSIM_MASK              0x1
#define PMU_RG_DEG_EN_PG_VSIM_SHIFT             0
#define PMU_RG_DEG_WND_PG_VSIM_ADDR             PMU_DIG_DEG_CFG_VSIM_0
#define PMU_RG_DEG_WND_PG_VSIM_MASK             0x1
#define PMU_RG_DEG_WND_PG_VSIM_SHIFT            1
#define PMU_RG_DEG_THD_PG_VSIM_ADDR             PMU_DIG_DEG_CFG_VSIM_0
#define PMU_RG_DEG_THD_PG_VSIM_MASK             0x3
#define PMU_RG_DEG_THD_PG_VSIM_SHIFT            3
#define PMU_RG_DEG_IN_PG_VSIM_ADDR              PMU_DIG_DEG_CFG_VSIM_0
#define PMU_RG_DEG_IN_PG_VSIM_MASK              0x1
#define PMU_RG_DEG_IN_PG_VSIM_SHIFT             5
#define PMU_RG_DEG_OUT_PG_VSIM_ADDR             PMU_DIG_DEG_CFG_VSIM_0
#define PMU_RG_DEG_OUT_PG_VSIM_MASK             0x1
#define PMU_RG_DEG_OUT_PG_VSIM_SHIFT            6
#define PMU_RG_DEG_EN_OC_VSIM_ADDR              PMU_DIG_DEG_CFG_VSIM_1
#define PMU_RG_DEG_EN_OC_VSIM_MASK              0x1
#define PMU_RG_DEG_EN_OC_VSIM_SHIFT             0
#define PMU_RG_DEG_WND_OC_VSIM_ADDR             PMU_DIG_DEG_CFG_VSIM_1
#define PMU_RG_DEG_WND_OC_VSIM_MASK             0x1
#define PMU_RG_DEG_WND_OC_VSIM_SHIFT            1
#define PMU_RG_DEG_THD_OC_VSIM_ADDR             PMU_DIG_DEG_CFG_VSIM_1
#define PMU_RG_DEG_THD_OC_VSIM_MASK             0x3
#define PMU_RG_DEG_THD_OC_VSIM_SHIFT            3
#define PMU_RG_DEG_IN_OC_VSIM_ADDR              PMU_DIG_DEG_CFG_VSIM_1
#define PMU_RG_DEG_IN_OC_VSIM_MASK              0x1
#define PMU_RG_DEG_IN_OC_VSIM_SHIFT             5
#define PMU_RG_DEG_OUT_OC_VSIM_ADDR             PMU_DIG_DEG_CFG_VSIM_1
#define PMU_RG_DEG_OUT_OC_VSIM_MASK             0x1
#define PMU_RG_DEG_OUT_OC_VSIM_SHIFT            6
#define PMU_RG_EN_HPBG_LPM_ADDR                 PMU_REG_BASE_CON0
#define PMU_RG_EN_HPBG_LPM_MASK                 0x1
#define PMU_RG_EN_HPBG_LPM_SHIFT                0
#define PMU_RG_EN_LSLP_MODE_ADDR                PMU_REG_BASE_CON0
#define PMU_RG_EN_LSLP_MODE_MASK                0x1
#define PMU_RG_EN_LSLP_MODE_SHIFT               1
#define PMU_RG_EN_LSLP_MODE_SW_SEL_ADDR         PMU_REG_BASE_CON0
#define PMU_RG_EN_LSLP_MODE_SW_SEL_MASK         0x1
#define PMU_RG_EN_LSLP_MODE_SW_SEL_SHIFT        2
#define PMU_RG_CLK_TRIM_ADDR                    PMU_REG_BASE_CON1
#define PMU_RG_CLK_TRIM_MASK                    0x1F
#define PMU_RG_CLK_TRIM_SHIFT                   0
#define PMU_RG_EN_LONGPRESS_ADDR                PMU_REG_BASE_CON1
#define PMU_RG_EN_LONGPRESS_MASK                0x1
#define PMU_RG_EN_LONGPRESS_SHIFT               5
#define PMU_RG_LONGPRESS_TYPE_SEL_ADDR          PMU_REG_BASE_CON1
#define PMU_RG_LONGPRESS_TYPE_SEL_MASK          0x1
#define PMU_RG_LONGPRESS_TYPE_SEL_SHIFT         6
#define PMU_RG_T_LONGPRESS_SEL_ADDR             PMU_REG_BASE_CON1
#define PMU_RG_T_LONGPRESS_SEL_MASK             0x3
#define PMU_RG_T_LONGPRESS_SEL_SHIFT            7
#define PMU_RG_THR_LS_THRESHOLD_SEL_ADDR        PMU_REG_BASE_CON1
#define PMU_RG_THR_LS_THRESHOLD_SEL_MASK        0x1
#define PMU_RG_THR_LS_THRESHOLD_SEL_SHIFT       9
#define PMU_RG_BGR_TCTRIM_HPBG_ADDR             PMU_REG_BASE_CON2
#define PMU_RG_BGR_TCTRIM_HPBG_MASK             0xF
#define PMU_RG_BGR_TCTRIM_HPBG_SHIFT            0
#define PMU_RG_VREF_TRIM_HPBG_ADDR              PMU_REG_BASE_CON2
#define PMU_RG_VREF_TRIM_HPBG_MASK              0xF
#define PMU_RG_VREF_TRIM_HPBG_SHIFT             4
#define PMU_RG_RSV_LATCH_SIG_ADDR               PMU_REG_BASE_CON2
#define PMU_RG_RSV_LATCH_SIG_MASK               0xFF
#define PMU_RG_RSV_LATCH_SIG_SHIFT              8
#define PMU_RG_LPBG_STUP_EN_ADDR                PMU_REG_BASE_CON3
#define PMU_RG_LPBG_STUP_EN_MASK                0x1
#define PMU_RG_LPBG_STUP_EN_SHIFT               0
#define PMU_RG_LPBG_STUP_IBDB_ADDR              PMU_REG_BASE_CON3
#define PMU_RG_LPBG_STUP_IBDB_MASK              0x1
#define PMU_RG_LPBG_STUP_IBDB_SHIFT             1
#define PMU_RG_LPBG_TCTRIM_ADDR                 PMU_REG_BASE_CON3
#define PMU_RG_LPBG_TCTRIM_MASK                 0x1F
#define PMU_RG_LPBG_TCTRIM_SHIFT                2
#define PMU_RG_LPBG_VREFTRIM_ADDR               PMU_REG_BASE_CON4
#define PMU_RG_LPBG_VREFTRIM_MASK               0x1F
#define PMU_RG_LPBG_VREFTRIM_SHIFT              0
#define PMU_RG_LPBG_IBTRIM_ADDR                 PMU_REG_BASE_CON4
#define PMU_RG_LPBG_IBTRIM_MASK                 0x1F
#define PMU_RG_LPBG_IBTRIM_SHIFT                5
#define PMU_RG_LPBG_RSV2_ADDR                   PMU_REG_BASE_CON4
#define PMU_RG_LPBG_RSV2_MASK                   0x7
#define PMU_RG_LPBG_RSV2_SHIFT                  10
#define PMU_RG_AO_LATCH_SET_ADDR                PMU_REG_BASE_CON5
#define PMU_RG_AO_LATCH_SET_MASK                0x1
#define PMU_RG_AO_LATCH_SET_SHIFT               0
#define PMU_RG_AO_LATCH_MASK_ADDR               PMU_REG_BASE_CON5
#define PMU_RG_AO_LATCH_MASK_MASK               0x1
#define PMU_RG_AO_LATCH_MASK_SHIFT              1
#define PMU_RG_VRF_EN_ADDR                      PMU_DIG_VRF_CON0
#define PMU_RG_VRF_EN_MASK                      0x1
#define PMU_RG_VRF_EN_SHIFT                     0
#define PMU_RG_VRF_EN_SW_SEL_ADDR               PMU_DIG_VRF_CON0
#define PMU_RG_VRF_EN_SW_SEL_MASK               0x1
#define PMU_RG_VRF_EN_SW_SEL_SHIFT              1
#define PMU_RG_VCORE_EN_ADDR                    PMU_DIG_VCORE_CON0
#define PMU_RG_VCORE_EN_MASK                    0x1
#define PMU_RG_VCORE_EN_SHIFT                   0
#define PMU_RG_VCORE_VOSEL_NM_ADDR              PMU_DIG_VCORE_CON1
#define PMU_RG_VCORE_VOSEL_NM_MASK              0x1F
#define PMU_RG_VCORE_VOSEL_NM_SHIFT             0
#define PMU_RG_VCORE_VOSEL_LPM_ADDR             PMU_DIG_VCORE_CON1
#define PMU_RG_VCORE_VOSEL_LPM_MASK             0x1F
#define PMU_RG_VCORE_VOSEL_LPM_SHIFT            5
#define PMU_RG_VCORE_IPK_OS_NM_ADDR             PMU_DIG_VCORE_CON2
#define PMU_RG_VCORE_IPK_OS_NM_MASK             0x7
#define PMU_RG_VCORE_IPK_OS_NM_SHIFT            0
#define PMU_RG_VCORE_IPK_OS_LPM_ADDR            PMU_DIG_VCORE_CON2
#define PMU_RG_VCORE_IPK_OS_LPM_MASK            0x7
#define PMU_RG_VCORE_IPK_OS_LPM_SHIFT           3
#define PMU_RG_VCORE_VOTRIM_NM_ADDR             PMU_DIG_VCORE_CON3
#define PMU_RG_VCORE_VOTRIM_NM_MASK             0xF
#define PMU_RG_VCORE_VOTRIM_NM_SHIFT            0
#define PMU_RG_VCORE_VOTRIM_LPM_ADDR            PMU_DIG_VCORE_CON3
#define PMU_RG_VCORE_VOTRIM_LPM_MASK            0xF
#define PMU_RG_VCORE_VOTRIM_LPM_SHIFT           4
#define PMU_RG_VCORE_DVS_REN_ADDR               PMU_DIG_VCORE_CON4
#define PMU_RG_VCORE_DVS_REN_MASK               0x1
#define PMU_RG_VCORE_DVS_REN_SHIFT              0
#define PMU_RG_VCORE_DVS_FEN_ADDR               PMU_DIG_VCORE_CON4
#define PMU_RG_VCORE_DVS_FEN_MASK               0x1
#define PMU_RG_VCORE_DVS_FEN_SHIFT              1
#define PMU_RG_VCORE_DVS_STEP_SEL_ADDR          PMU_DIG_VCORE_CON4
#define PMU_RG_VCORE_DVS_STEP_SEL_MASK          0x1
#define PMU_RG_VCORE_DVS_STEP_SEL_SHIFT         2
#define PMU_RG_VCORE_DVS_ACK_ADDR               PMU_DIG_VCORE_CON4
#define PMU_RG_VCORE_DVS_ACK_MASK               0x1
#define PMU_RG_VCORE_DVS_ACK_SHIFT              3
#define PMU_RG_BUCK_VPA_EN_ADDR                 PMU_DIG_VPA_CON0
#define PMU_RG_BUCK_VPA_EN_MASK                 0x1
#define PMU_RG_BUCK_VPA_EN_SHIFT                0
#define PMU_RG_BUCK_VPA_VOSEL_ADDR              PMU_DIG_VPA_CON1
#define PMU_RG_BUCK_VPA_VOSEL_MASK              0x3F
#define PMU_RG_BUCK_VPA_VOSEL_SHIFT             0
#define PMU_RG_BUCK_VPA_VOSEL_DLC111_ADDR       PMU_DIG_VPA_CON2
#define PMU_RG_BUCK_VPA_VOSEL_DLC111_MASK       0x3F
#define PMU_RG_BUCK_VPA_VOSEL_DLC111_SHIFT      0
#define PMU_RG_BUCK_VPA_VOSEL_DLC011_ADDR       PMU_DIG_VPA_CON2
#define PMU_RG_BUCK_VPA_VOSEL_DLC011_MASK       0x3F
#define PMU_RG_BUCK_VPA_VOSEL_DLC011_SHIFT      6
#define PMU_RG_BUCK_VPA_VOSEL_DLC001_ADDR       PMU_DIG_VPA_CON3
#define PMU_RG_BUCK_VPA_VOSEL_DLC001_MASK       0x3F
#define PMU_RG_BUCK_VPA_VOSEL_DLC001_SHIFT      0
#define PMU_RG_BUCK_VPA_SFCHG_REN_ADDR          PMU_DIG_VPA_CON4
#define PMU_RG_BUCK_VPA_SFCHG_REN_MASK          0x1
#define PMU_RG_BUCK_VPA_SFCHG_REN_SHIFT         0
#define PMU_RG_BUCK_VPA_SFCHG_RRATE_ADDR        PMU_DIG_VPA_CON4
#define PMU_RG_BUCK_VPA_SFCHG_RRATE_MASK        0x7F
#define PMU_RG_BUCK_VPA_SFCHG_RRATE_SHIFT       1
#define PMU_RG_BUCK_VPA_SFCHG_FEN_ADDR          PMU_DIG_VPA_CON4
#define PMU_RG_BUCK_VPA_SFCHG_FEN_MASK          0x1
#define PMU_RG_BUCK_VPA_SFCHG_FEN_SHIFT         8
#define PMU_RG_BUCK_VPA_SFCHG_FRATE_ADDR        PMU_DIG_VPA_CON4
#define PMU_RG_BUCK_VPA_SFCHG_FRATE_MASK        0x7F
#define PMU_RG_BUCK_VPA_SFCHG_FRATE_SHIFT       9
#define PMU_RG_BUCK_VPA_DVS_BW_ONCE_ADDR        PMU_DIG_VPA_CON5
#define PMU_RG_BUCK_VPA_DVS_BW_ONCE_MASK        0x1
#define PMU_RG_BUCK_VPA_DVS_BW_ONCE_SHIFT       0
#define PMU_RG_BUCK_VPA_DVS_BW_CTRL_ADDR        PMU_DIG_VPA_CON5
#define PMU_RG_BUCK_VPA_DVS_BW_CTRL_MASK        0x3
#define PMU_RG_BUCK_VPA_DVS_BW_CTRL_SHIFT       1
#define PMU_RG_BUCK_VPA_DVS_BW_TD_ADDR          PMU_DIG_VPA_CON5
#define PMU_RG_BUCK_VPA_DVS_BW_TD_MASK          0x3
#define PMU_RG_BUCK_VPA_DVS_BW_TD_SHIFT         3
#define PMU_RG_BUCK_VPA_DVS_TRANST_ONCE_ADDR    PMU_DIG_VPA_CON5
#define PMU_RG_BUCK_VPA_DVS_TRANST_ONCE_MASK    0x1
#define PMU_RG_BUCK_VPA_DVS_TRANST_ONCE_SHIFT   5
#define PMU_RG_BUCK_VPA_DVS_TRANST_CTRL_ADDR    PMU_DIG_VPA_CON5
#define PMU_RG_BUCK_VPA_DVS_TRANST_CTRL_MASK    0x3
#define PMU_RG_BUCK_VPA_DVS_TRANST_CTRL_SHIFT   6
#define PMU_RG_BUCK_VPA_DVS_TRANST_TD_ADDR      PMU_DIG_VPA_CON5
#define PMU_RG_BUCK_VPA_DVS_TRANST_TD_MASK      0x3
#define PMU_RG_BUCK_VPA_DVS_TRANST_TD_SHIFT     8
#define PMU_RG_BUCK_VPA_OC_SDN_EN_ADDR          PMU_DIG_VPA_CON7
#define PMU_RG_BUCK_VPA_OC_SDN_EN_MASK          0x1
#define PMU_RG_BUCK_VPA_OC_SDN_EN_SHIFT         0
#define PMU_RG_BUCK_VPA_OC_SDN_EN_SEL_ADDR      PMU_DIG_VPA_CON7
#define PMU_RG_BUCK_VPA_OC_SDN_EN_SEL_MASK      0x1
#define PMU_RG_BUCK_VPA_OC_SDN_EN_SEL_SHIFT     1
#define PMU_RG_BUCK_VPA_STB_MAX_ADDR            PMU_DIG_VPA_CON7
#define PMU_RG_BUCK_VPA_STB_MAX_MASK            0x1FF
#define PMU_RG_BUCK_VPA_STB_MAX_SHIFT           2
#define PMU_RG_BUCK_VPA_DLC_MAP_EN_ADDR         PMU_DIG_VPA_CON8
#define PMU_RG_BUCK_VPA_DLC_MAP_EN_MASK         0x1
#define PMU_RG_BUCK_VPA_DLC_MAP_EN_SHIFT        0
#define PMU_RG_BUCK_VPA_DLC_ADDR                PMU_DIG_VPA_CON8
#define PMU_RG_BUCK_VPA_DLC_MASK                0x7
#define PMU_RG_BUCK_VPA_DLC_SHIFT               1
#define PMU_RG_BUCK_VPA_MSFG_EN_ADDR            PMU_DIG_VPA_CON9
#define PMU_RG_BUCK_VPA_MSFG_EN_MASK            0x1
#define PMU_RG_BUCK_VPA_MSFG_EN_SHIFT           0
#define PMU_RG_BUCK_VPA_MSFG_RDELTA2GO_ADDR     PMU_DIG_VPA_CON10
#define PMU_RG_BUCK_VPA_MSFG_RDELTA2GO_MASK     0x3F
#define PMU_RG_BUCK_VPA_MSFG_RDELTA2GO_SHIFT    0
#define PMU_RG_BUCK_VPA_MSFG_FDELTA2GO_ADDR     PMU_DIG_VPA_CON10
#define PMU_RG_BUCK_VPA_MSFG_FDELTA2GO_MASK     0x3F
#define PMU_RG_BUCK_VPA_MSFG_FDELTA2GO_SHIFT    6
#define PMU_RG_BUCK_VPA_MSFG_RRATE0_ADDR        PMU_DIG_VPA_CON11
#define PMU_RG_BUCK_VPA_MSFG_RRATE0_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_RRATE0_SHIFT       0
#define PMU_RG_BUCK_VPA_MSFG_RRATE1_ADDR        PMU_DIG_VPA_CON11
#define PMU_RG_BUCK_VPA_MSFG_RRATE1_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_RRATE1_SHIFT       6
#define PMU_RG_BUCK_VPA_MSFG_RRATE2_ADDR        PMU_DIG_VPA_CON12
#define PMU_RG_BUCK_VPA_MSFG_RRATE2_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_RRATE2_SHIFT       0
#define PMU_RG_BUCK_VPA_MSFG_RRATE3_ADDR        PMU_DIG_VPA_CON12
#define PMU_RG_BUCK_VPA_MSFG_RRATE3_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_RRATE3_SHIFT       6
#define PMU_RG_BUCK_VPA_MSFG_RRATE4_ADDR        PMU_DIG_VPA_CON13
#define PMU_RG_BUCK_VPA_MSFG_RRATE4_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_RRATE4_SHIFT       0
#define PMU_RG_BUCK_VPA_MSFG_RRATE5_ADDR        PMU_DIG_VPA_CON13
#define PMU_RG_BUCK_VPA_MSFG_RRATE5_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_RRATE5_SHIFT       6
#define PMU_RG_BUCK_VPA_MSFG_RTHD0_ADDR         PMU_DIG_VPA_CON14
#define PMU_RG_BUCK_VPA_MSFG_RTHD0_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_RTHD0_SHIFT        0
#define PMU_RG_BUCK_VPA_MSFG_RTHD1_ADDR         PMU_DIG_VPA_CON14
#define PMU_RG_BUCK_VPA_MSFG_RTHD1_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_RTHD1_SHIFT        6
#define PMU_RG_BUCK_VPA_MSFG_RTHD2_ADDR         PMU_DIG_VPA_CON15
#define PMU_RG_BUCK_VPA_MSFG_RTHD2_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_RTHD2_SHIFT        0
#define PMU_RG_BUCK_VPA_MSFG_RTHD3_ADDR         PMU_DIG_VPA_CON15
#define PMU_RG_BUCK_VPA_MSFG_RTHD3_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_RTHD3_SHIFT        6
#define PMU_RG_BUCK_VPA_MSFG_RTHD4_ADDR         PMU_DIG_VPA_CON16
#define PMU_RG_BUCK_VPA_MSFG_RTHD4_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_RTHD4_SHIFT        0
#define PMU_RG_BUCK_VPA_MSFG_FRATE0_ADDR        PMU_DIG_VPA_CON17
#define PMU_RG_BUCK_VPA_MSFG_FRATE0_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_FRATE0_SHIFT       0
#define PMU_RG_BUCK_VPA_MSFG_FRATE1_ADDR        PMU_DIG_VPA_CON17
#define PMU_RG_BUCK_VPA_MSFG_FRATE1_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_FRATE1_SHIFT       6
#define PMU_RG_BUCK_VPA_MSFG_FRATE2_ADDR        PMU_DIG_VPA_CON18
#define PMU_RG_BUCK_VPA_MSFG_FRATE2_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_FRATE2_SHIFT       0
#define PMU_RG_BUCK_VPA_MSFG_FRATE3_ADDR        PMU_DIG_VPA_CON18
#define PMU_RG_BUCK_VPA_MSFG_FRATE3_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_FRATE3_SHIFT       6
#define PMU_RG_BUCK_VPA_MSFG_FRATE4_ADDR        PMU_DIG_VPA_CON19
#define PMU_RG_BUCK_VPA_MSFG_FRATE4_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_FRATE4_SHIFT       0
#define PMU_RG_BUCK_VPA_MSFG_FRATE5_ADDR        PMU_DIG_VPA_CON19
#define PMU_RG_BUCK_VPA_MSFG_FRATE5_MASK        0x3F
#define PMU_RG_BUCK_VPA_MSFG_FRATE5_SHIFT       6
#define PMU_RG_BUCK_VPA_MSFG_FTHD0_ADDR         PMU_DIG_VPA_CON20
#define PMU_RG_BUCK_VPA_MSFG_FTHD0_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_FTHD0_SHIFT        0
#define PMU_RG_BUCK_VPA_MSFG_FTHD1_ADDR         PMU_DIG_VPA_CON20
#define PMU_RG_BUCK_VPA_MSFG_FTHD1_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_FTHD1_SHIFT        6
#define PMU_RG_BUCK_VPA_MSFG_FTHD2_ADDR         PMU_DIG_VPA_CON21
#define PMU_RG_BUCK_VPA_MSFG_FTHD2_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_FTHD2_SHIFT        0
#define PMU_RG_BUCK_VPA_MSFG_FTHD3_ADDR         PMU_DIG_VPA_CON21
#define PMU_RG_BUCK_VPA_MSFG_FTHD3_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_FTHD3_SHIFT        6
#define PMU_RG_BUCK_VPA_MSFG_FTHD4_ADDR         PMU_DIG_VPA_CON22
#define PMU_RG_BUCK_VPA_MSFG_FTHD4_MASK         0x3F
#define PMU_RG_BUCK_VPA_MSFG_FTHD4_SHIFT        0
#define PMU_RG_VIO18_EN_ADDR                    PMU_DIG_VIO18_CON0
#define PMU_RG_VIO18_EN_MASK                    0x1
#define PMU_RG_VIO18_EN_SHIFT                   0
#define PMU_RG_VIO18_VOTRIM_NM_ADDR             PMU_DIG_VIO18_CON1
#define PMU_RG_VIO18_VOTRIM_NM_MASK             0xF
#define PMU_RG_VIO18_VOTRIM_NM_SHIFT            0
#define PMU_RG_VIO18_VOTRIM_LPM_ADDR            PMU_DIG_VIO18_CON1
#define PMU_RG_VIO18_VOTRIM_LPM_MASK            0xF
#define PMU_RG_VIO18_VOTRIM_LPM_SHIFT           4
#define PMU_RG_VSIM_VOTRIM_NM_ADDR              PMU_DIG_VSIM_CON0
#define PMU_RG_VSIM_VOTRIM_NM_MASK              0xF
#define PMU_RG_VSIM_VOTRIM_NM_SHIFT             0
#define PMU_RG_VSIM_VOTRIM_LPM_ADDR             PMU_DIG_VSIM_CON0
#define PMU_RG_VSIM_VOTRIM_LPM_MASK             0xF
#define PMU_RG_VSIM_VOTRIM_LPM_SHIFT            4
#define PMU_RG_VSRAM_EN_ADDR                    PMU_DIG_SRAM_CON0
#define PMU_RG_VSRAM_EN_MASK                    0x1
#define PMU_RG_VSRAM_EN_SHIFT                   0
#define PMU_RG_VSRAM_DVS_REN_ADDR               PMU_DIG_SRAM_CON1
#define PMU_RG_VSRAM_DVS_REN_MASK               0x1
#define PMU_RG_VSRAM_DVS_REN_SHIFT              0
#define PMU_RG_VSRAM_DVS_FEN_ADDR               PMU_DIG_SRAM_CON1
#define PMU_RG_VSRAM_DVS_FEN_MASK               0x1
#define PMU_RG_VSRAM_DVS_FEN_SHIFT              1
#define PMU_RG_VSRAM_DVS_ACK_ADDR               PMU_DIG_SRAM_CON1
#define PMU_RG_VSRAM_DVS_ACK_MASK               0x1
#define PMU_RG_VSRAM_DVS_ACK_SHIFT              3
#define PMU_RG_VSRAM_VOSEL_NM_ADDR              PMU_DIG_SRAM_CON2
#define PMU_RG_VSRAM_VOSEL_NM_MASK              0x1F
#define PMU_RG_VSRAM_VOSEL_NM_SHIFT             0
#define PMU_RG_VSRAM_VOSEL_SLP_ADDR             PMU_DIG_SRAM_CON2
#define PMU_RG_VSRAM_VOSEL_SLP_MASK             0x1F
#define PMU_RG_VSRAM_VOSEL_SLP_SHIFT            5
#define PMU_RG_VSRAM_VOTRIM_NM_ADDR             PMU_DIG_SRAM_CON3
#define PMU_RG_VSRAM_VOTRIM_NM_MASK             0xF
#define PMU_RG_VSRAM_VOTRIM_NM_SHIFT            0
#define PMU_RG_VSRAM_VOTRIM_LPM_ADDR            PMU_DIG_SRAM_CON3
#define PMU_RG_VSRAM_VOTRIM_LPM_MASK            0xF
#define PMU_RG_VSRAM_VOTRIM_LPM_SHIFT           4
#define PMU_RG_VSRAM_NDIS_EN_ADDR               PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_NDIS_EN_MASK               0x1
#define PMU_RG_VSRAM_NDIS_EN_SHIFT              0
#define PMU_RG_VSRAM_RSV1_ADDR                  PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_RSV1_MASK                  0x3
#define PMU_RG_VSRAM_RSV1_SHIFT                 1
#define PMU_RG_VSRAM_RSV2_ADDR                  PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_RSV2_MASK                  0x3
#define PMU_RG_VSRAM_RSV2_SHIFT                 3
#define PMU_RG_VSRAM_LEAKCOMP_EN_ADDR           PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_LEAKCOMP_EN_MASK           0x1
#define PMU_RG_VSRAM_LEAKCOMP_EN_SHIFT          5
#define PMU_RG_VSRAM_OC_EN_ADDR                 PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_OC_EN_MASK                 0x1
#define PMU_RG_VSRAM_OC_EN_SHIFT                6
#define PMU_RG_VSRAM_LEAKCOMP_BP_ADDR           PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_LEAKCOMP_BP_MASK           0x1
#define PMU_RG_VSRAM_LEAKCOMP_BP_SHIFT          7
#define PMU_RG_VSRAM_OC_SEL_ADDR                PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_OC_SEL_MASK                0x7
#define PMU_RG_VSRAM_OC_SEL_SHIFT               8
#define PMU_RG_VSRAM_HP_EN_ADDR                 PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_HP_EN_MASK                 0x1
#define PMU_RG_VSRAM_HP_EN_SHIFT                11
#define PMU_RG_VSRAM_PG_EN_ADDR                 PMU_DIG_SRAM_CON4
#define PMU_RG_VSRAM_PG_EN_MASK                 0x1
#define PMU_RG_VSRAM_PG_EN_SHIFT                12
#define PMU_RG_IBIAS_TRIM_HPBG_ADDR             DIG_VCORE_ANA_CON0
#define PMU_RG_IBIAS_TRIM_HPBG_MASK             0xF
#define PMU_RG_IBIAS_TRIM_HPBG_SHIFT            0
#define PMU_RG_HPBG_RSV_ADDR                    DIG_VCORE_ANA_CON1
#define PMU_RG_HPBG_RSV_MASK                    0x1F
#define PMU_RG_HPBG_RSV_SHIFT                   0
#define PMU_RG_VPA_VHSEL_ADDR                   DIG_VCORE_ANA_CON1
#define PMU_RG_VPA_VHSEL_MASK                   0x3
#define PMU_RG_VPA_VHSEL_SHIFT                  5
#define PMU_RG_VPA_VLSEL_ADDR                   DIG_VCORE_ANA_CON1
#define PMU_RG_VPA_VLSEL_MASK                   0x3
#define PMU_RG_VPA_VLSEL_SHIFT                  7
#define PMU_RG_LPBG_RSV1_ADDR                   DIG_VCORE_ANA_CON1
#define PMU_RG_LPBG_RSV1_MASK                   0x7
#define PMU_RG_LPBG_RSV1_SHIFT                  9
#define PMU_RG_LPBG_TM_EN_ADDR                  DIG_VCORE_ANA_CON1
#define PMU_RG_LPBG_TM_EN_MASK                  0x1
#define PMU_RG_LPBG_TM_EN_SHIFT                 12
#define PMU_RG_HPBG_TM_EN_ADDR                  DIG_VCORE_ANA_CON1
#define PMU_RG_HPBG_TM_EN_MASK                  0x1
#define PMU_RG_HPBG_TM_EN_SHIFT                 13
#define PMU_RG_THR_TM_EN_ADDR                   DIG_VCORE_ANA_CON1
#define PMU_RG_THR_TM_EN_MASK                   0x1
#define PMU_RG_THR_TM_EN_SHIFT                  14
#define PMU_RG_HPBG_TM_SEL_ADDR                 DIG_VCORE_ANA_CON2
#define PMU_RG_HPBG_TM_SEL_MASK                 0x3
#define PMU_RG_HPBG_TM_SEL_SHIFT                0
#define PMU_RG_ABB_REFINPUT_SEL_ADDR            DIG_VCORE_ANA_CON2
#define PMU_RG_ABB_REFINPUT_SEL_MASK            0x1
#define PMU_RG_ABB_REFINPUT_SEL_SHIFT           2
#define PMU_RG_VRF_VOSEL_ADDR                   DIG_VCORE_ANA_CON3
#define PMU_RG_VRF_VOSEL_MASK                   0xF
#define PMU_RG_VRF_VOSEL_SHIFT                  0
#define PMU_RG_VRF_VOTRIM_ADDR                  DIG_VCORE_ANA_CON3
#define PMU_RG_VRF_VOTRIM_MASK                  0xF
#define PMU_RG_VRF_VOTRIM_SHIFT                 4
#define PMU_RG_VRF_ZXOS_ADDR                    DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_ZXOS_MASK                    0x3
#define PMU_RG_VRF_ZXOS_SHIFT                   0
#define PMU_RG_VRF_LGSR_ADDR                    DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_LGSR_MASK                    0x3
#define PMU_RG_VRF_LGSR_SHIFT                   2
#define PMU_RG_VRF_UGSR_ADDR                    DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_UGSR_MASK                    0x3
#define PMU_RG_VRF_UGSR_SHIFT                   4
#define PMU_RG_VRF_IPK_SEL_ADDR                 DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_IPK_SEL_MASK                 0x7
#define PMU_RG_VRF_IPK_SEL_SHIFT                6
#define PMU_RG_VRF_ADJIPK_EN_ADDR               DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_ADJIPK_EN_MASK               0x1
#define PMU_RG_VRF_ADJIPK_EN_SHIFT              9
#define PMU_RG_VRF_NM_IBSEL_ADDR                DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_NM_IBSEL_MASK                0x7
#define PMU_RG_VRF_NM_IBSEL_SHIFT               10
#define PMU_RG_VRF_CPPFM_HYST_ADDR              DIG_VCORE_ANA_CON4
#define PMU_RG_VRF_CPPFM_HYST_MASK              0x3
#define PMU_RG_VRF_CPPFM_HYST_SHIFT             13
#define PMU_RG_VRF_IPK_OS_ADDR                  DIG_VCORE_ANA_CON5
#define PMU_RG_VRF_IPK_OS_MASK                  0x7
#define PMU_RG_VRF_IPK_OS_SHIFT                 0
#define PMU_RG_VRF_DP_HYST_ADDR                 DIG_VCORE_ANA_CON5
#define PMU_RG_VRF_DP_HYST_MASK                 0x3
#define PMU_RG_VRF_DP_HYST_SHIFT                3
#define PMU_RG_VRF_RSV1_ADDR                    DIG_VCORE_ANA_CON5
#define PMU_RG_VRF_RSV1_MASK                    0xFF
#define PMU_RG_VRF_RSV1_SHIFT                   5
#define PMU_RG_VRF_RSV2_ADDR                    DIG_VCORE_ANA_CON6
#define PMU_RG_VRF_RSV2_MASK                    0xFF
#define PMU_RG_VRF_RSV2_SHIFT                   0
#define PMU_RG_VRF_NDIS_EN_ADDR                 DIG_VCORE_ANA_CON6
#define PMU_RG_VRF_NDIS_EN_MASK                 0x1
#define PMU_RG_VRF_NDIS_EN_SHIFT                8
#define PMU_RG_VRF_PWR_STG_TM_ADDR              DIG_VCORE_ANA_CON6
#define PMU_RG_VRF_PWR_STG_TM_MASK              0x3
#define PMU_RG_VRF_PWR_STG_TM_SHIFT             9
#define PMU_RG_VRF_NM_ADJIB_EN_ADDR             DIG_VCORE_ANA_CON6
#define PMU_RG_VRF_NM_ADJIB_EN_MASK             0x1
#define PMU_RG_VRF_NM_ADJIB_EN_SHIFT            11
#define PMU_RG_VRF_PG_EN_ADDR                   DIG_VCORE_ANA_CON6
#define PMU_RG_VRF_PG_EN_MASK                   0x1
#define PMU_RG_VRF_PG_EN_SHIFT                  12
#define PMU_RG_T_VRF_SS_SEL_ADDR                DIG_VCORE_ANA_CON6
#define PMU_RG_T_VRF_SS_SEL_MASK                0x1
#define PMU_RG_T_VRF_SS_SEL_SHIFT               13
#define PMU_RG_VCORE_CPPFM_IHDSEL_ADDR          DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_CPPFM_IHDSEL_MASK          0x3
#define PMU_RG_VCORE_CPPFM_IHDSEL_SHIFT         0
#define PMU_RG_VCORE_CPPFM_HYST_ADDR            DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_CPPFM_HYST_MASK            0x3
#define PMU_RG_VCORE_CPPFM_HYST_SHIFT           2
#define PMU_RG_VCORE_ZXOS_ADDR                  DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_ZXOS_MASK                  0x3
#define PMU_RG_VCORE_ZXOS_SHIFT                 4
#define PMU_RG_VCORE_IPK_SEL_ADDR               DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_IPK_SEL_MASK               0x7
#define PMU_RG_VCORE_IPK_SEL_SHIFT              6
#define PMU_RG_VCORE_ADJIPK_EN_ADDR             DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_ADJIPK_EN_MASK             0x1
#define PMU_RG_VCORE_ADJIPK_EN_SHIFT            9
#define PMU_RG_VCORE_DP_HYST_ADDR               DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_DP_HYST_MASK               0x3
#define PMU_RG_VCORE_DP_HYST_SHIFT              10
#define PMU_RG_VCORE_PWR_STG_TM_ADDR            DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_PWR_STG_TM_MASK            0x3
#define PMU_RG_VCORE_PWR_STG_TM_SHIFT           12
#define PMU_RG_VCORE_LGSR_ADDR                  DIG_VCORE_ANA_CON7
#define PMU_RG_VCORE_LGSR_MASK                  0x3
#define PMU_RG_VCORE_LGSR_SHIFT                 14
#define PMU_RG_VCORE_UGSR_ADDR                  DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_UGSR_MASK                  0x3
#define PMU_RG_VCORE_UGSR_SHIFT                 0
#define PMU_RG_VCORE_NDIS_EN_ADDR               DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_NDIS_EN_MASK               0x1
#define PMU_RG_VCORE_NDIS_EN_SHIFT              2
#define PMU_RG_VCORE_LPM_ADJIB_EN_ADDR          DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_LPM_ADJIB_EN_MASK          0x1
#define PMU_RG_VCORE_LPM_ADJIB_EN_SHIFT         3
#define PMU_RG_VCORE_LPM_IBSEL_ADDR             DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_LPM_IBSEL_MASK             0x7
#define PMU_RG_VCORE_LPM_IBSEL_SHIFT            4
#define PMU_RG_VCORE_NM_ADJIB_EN_ADDR           DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_NM_ADJIB_EN_MASK           0x1
#define PMU_RG_VCORE_NM_ADJIB_EN_SHIFT          7
#define PMU_RG_T_VCORE_SS_SEL_ADDR              DIG_VCORE_ANA_CON8
#define PMU_RG_T_VCORE_SS_SEL_MASK              0x1
#define PMU_RG_T_VCORE_SS_SEL_SHIFT             8
#define PMU_RG_VCORE_PG_EN_ADDR                 DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_PG_EN_MASK                 0x1
#define PMU_RG_VCORE_PG_EN_SHIFT                9
#define PMU_RG_VCORE_NM_IBSEL_ADDR              DIG_VCORE_ANA_CON8
#define PMU_RG_VCORE_NM_IBSEL_MASK              0x7
#define PMU_RG_VCORE_NM_IBSEL_SHIFT             10
#define PMU_RG_VCORE_RSV1_ADDR                  DIG_VCORE_ANA_CON9
#define PMU_RG_VCORE_RSV1_MASK                  0xFF
#define PMU_RG_VCORE_RSV1_SHIFT                 0
#define PMU_RG_VCORE_RSV2_ADDR                  DIG_VCORE_ANA_CON9
#define PMU_RG_VCORE_RSV2_MASK                  0xFF
#define PMU_RG_VCORE_RSV2_SHIFT                 8
#define PMU_RG_VFEM_VOCAL_ADDR                  DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_VOCAL_MASK                  0xF
#define PMU_RG_VFEM_VOCAL_SHIFT                 0
#define PMU_RG_VFEM_VOTRIM_ADDR                 DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_VOTRIM_MASK                 0xF
#define PMU_RG_VFEM_VOTRIM_SHIFT                4
#define PMU_RG_VFEM_LEAKCOMP_BP_ADDR            DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_LEAKCOMP_BP_MASK            0x1
#define PMU_RG_VFEM_LEAKCOMP_BP_SHIFT           8
#define PMU_RG_VFEM_LEAKCOMP_EN_ADDR            DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_LEAKCOMP_EN_MASK            0x1
#define PMU_RG_VFEM_LEAKCOMP_EN_SHIFT           9
#define PMU_RG_VFEM_NDIS_EN_ADDR                DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_NDIS_EN_MASK                0x1
#define PMU_RG_VFEM_NDIS_EN_SHIFT               10
#define PMU_RG_VFEM_PG_EN_ADDR                  DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_PG_EN_MASK                  0x1
#define PMU_RG_VFEM_PG_EN_SHIFT                 11
#define PMU_RG_VFEM_RSV1_ADDR                   DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_RSV1_MASK                   0x3
#define PMU_RG_VFEM_RSV1_SHIFT                  12
#define PMU_RG_VFEM_OC_EN_ADDR                  DIG_VCORE_ANA_CON10
#define PMU_RG_VFEM_OC_EN_MASK                  0x1
#define PMU_RG_VFEM_OC_EN_SHIFT                 14
#define PMU_RG_VFEM_OC_SEL_ADDR                 DIG_VCORE_ANA_CON11
#define PMU_RG_VFEM_OC_SEL_MASK                 0x7
#define PMU_RG_VFEM_OC_SEL_SHIFT                0
#define PMU_RG_VFEM_HP_EN_ADDR                  DIG_VCORE_ANA_CON11
#define PMU_RG_VFEM_HP_EN_MASK                  0x1
#define PMU_RG_VFEM_HP_EN_SHIFT                 3
#define PMU_RG_VFEM_RSV2_ADDR                   DIG_VCORE_ANA_CON11
#define PMU_RG_VFEM_RSV2_MASK                   0x3
#define PMU_RG_VFEM_RSV2_SHIFT                  4
#define PMU_RG_VFEM_EN_ADDR                     DIG_VCORE_ANA_CON12
#define PMU_RG_VFEM_EN_MASK                     0x1
#define PMU_RG_VFEM_EN_SHIFT                    0
#define PMU_RG_VIO18_VOCAL_ADDR                 DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_VOCAL_MASK                 0xF
#define PMU_RG_VIO18_VOCAL_SHIFT                0
#define PMU_RG_VIO18_LEAKCOMP_BP_ADDR           DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_LEAKCOMP_BP_MASK           0x1
#define PMU_RG_VIO18_LEAKCOMP_BP_SHIFT          4
#define PMU_RG_VIO18_LEAKCOMP_EN_ADDR           DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_LEAKCOMP_EN_MASK           0x1
#define PMU_RG_VIO18_LEAKCOMP_EN_SHIFT          5
#define PMU_RG_VIO18_NDIS_EN_ADDR               DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_NDIS_EN_MASK               0x1
#define PMU_RG_VIO18_NDIS_EN_SHIFT              6
#define PMU_RG_VIO18_HP_EN_ADDR                 DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_HP_EN_MASK                 0x1
#define PMU_RG_VIO18_HP_EN_SHIFT                7
#define PMU_RG_VIO18_PG_EN_ADDR                 DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_PG_EN_MASK                 0x1
#define PMU_RG_VIO18_PG_EN_SHIFT                8
#define PMU_RG_VIO18_OC_EN_ADDR                 DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_OC_EN_MASK                 0x1
#define PMU_RG_VIO18_OC_EN_SHIFT                9
#define PMU_RG_VIO18_OC_SEL_ADDR                DIG_VCORE_ANA_CON13
#define PMU_RG_VIO18_OC_SEL_MASK                0x7
#define PMU_RG_VIO18_OC_SEL_SHIFT               10
#define PMU_RG_VIO18_RSV1_ADDR                  DIG_VCORE_ANA_CON14
#define PMU_RG_VIO18_RSV1_MASK                  0x3
#define PMU_RG_VIO18_RSV1_SHIFT                 0
#define PMU_RG_VIO18_RSV2_ADDR                  DIG_VCORE_ANA_CON14
#define PMU_RG_VIO18_RSV2_MASK                  0x3
#define PMU_RG_VIO18_RSV2_SHIFT                 2
#define PMU_RG_VSIM_VOCAL_ADDR                  DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_VOCAL_MASK                  0xF
#define PMU_RG_VSIM_VOCAL_SHIFT                 0
#define PMU_RG_VSIM_VOSEL_ADDR                  DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_VOSEL_MASK                  0x3
#define PMU_RG_VSIM_VOSEL_SHIFT                 4
#define PMU_RG_VSIM_LEAKCOMP_BP_ADDR            DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_LEAKCOMP_BP_MASK            0x1
#define PMU_RG_VSIM_LEAKCOMP_BP_SHIFT           6
#define PMU_RG_VSIM_LEAKCOMP_EN_ADDR            DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_LEAKCOMP_EN_MASK            0x1
#define PMU_RG_VSIM_LEAKCOMP_EN_SHIFT           7
#define PMU_RG_VSIM_NDIS_EN_ADDR                DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_NDIS_EN_MASK                0x1
#define PMU_RG_VSIM_NDIS_EN_SHIFT               8
#define PMU_RG_VSIM_HP_EN_ADDR                  DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_HP_EN_MASK                  0x1
#define PMU_RG_VSIM_HP_EN_SHIFT                 9
#define PMU_RG_VSIM_PG_EN_ADDR                  DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_PG_EN_MASK                  0x1
#define PMU_RG_VSIM_PG_EN_SHIFT                 10
#define PMU_RG_VSIM_RSV1_ADDR                   DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_RSV1_MASK                   0x3
#define PMU_RG_VSIM_RSV1_SHIFT                  11
#define PMU_RG_VSIM_OC_EN_ADDR                  DIG_VCORE_ANA_CON15
#define PMU_RG_VSIM_OC_EN_MASK                  0x1
#define PMU_RG_VSIM_OC_EN_SHIFT                 13
#define PMU_RG_VSIM_OC_SEL_ADDR                 DIG_VCORE_ANA_CON16
#define PMU_RG_VSIM_OC_SEL_MASK                 0x7
#define PMU_RG_VSIM_OC_SEL_SHIFT                0
#define PMU_RG_VSIM_RSV2_ADDR                   DIG_VCORE_ANA_CON16
#define PMU_RG_VSIM_RSV2_MASK                   0x3
#define PMU_RG_VSIM_RSV2_SHIFT                  3
#define PMU_RG_VSIM_EN_ADDR                     DIG_VCORE_ANA_CON17
#define PMU_RG_VSIM_EN_MASK                     0x1
#define PMU_RG_VSIM_EN_SHIFT                    0
#define PMU_RG_VPA_NDIS_EN_ADDR                 DIG_VCORE_ANA_CON17
#define PMU_RG_VPA_NDIS_EN_MASK                 0x1
#define PMU_RG_VPA_NDIS_EN_SHIFT                1
#define PMU_RG_VPA_MODESET_ADDR                 DIG_VCORE_ANA_CON17
#define PMU_RG_VPA_MODESET_MASK                 0x1
#define PMU_RG_VPA_MODESET_SHIFT                2
#define PMU_RG_VPA_CC_ADDR                      DIG_VCORE_ANA_CON17
#define PMU_RG_VPA_CC_MASK                      0x3
#define PMU_RG_VPA_CC_SHIFT                     3
#define PMU_RG_VPA_CSR_ADDR                     DIG_VCORE_ANA_CON17
#define PMU_RG_VPA_CSR_MASK                     0x3
#define PMU_RG_VPA_CSR_SHIFT                    5
#define PMU_RG_VPA_CSMIR_ADDR                   DIG_VCORE_ANA_CON17
#define PMU_RG_VPA_CSMIR_MASK                   0x3
#define PMU_RG_VPA_CSMIR_SHIFT                  7
#define PMU_RG_VPA_CSL_ADDR                     DIG_VCORE_ANA_CON17
#define PMU_RG_VPA_CSL_MASK                     0x3
#define PMU_RG_VPA_CSL_SHIFT                    9
#define PMU_RG_VPA_SLP_ADDR                     DIG_VCORE_ANA_CON18
#define PMU_RG_VPA_SLP_MASK                     0x3
#define PMU_RG_VPA_SLP_SHIFT                    0
#define PMU_RG_VPA_AZC_EN_ADDR                  DIG_VCORE_ANA_CON18
#define PMU_RG_VPA_AZC_EN_MASK                  0x1
#define PMU_RG_VPA_AZC_EN_SHIFT                 2
#define PMU_RG_VPA_CP_FWUPOFF_ADDR              DIG_VCORE_ANA_CON18
#define PMU_RG_VPA_CP_FWUPOFF_MASK              0x1
#define PMU_RG_VPA_CP_FWUPOFF_SHIFT             3
#define PMU_RG_VPA_AZC_DELAY_ADDR               DIG_VCORE_ANA_CON18
#define PMU_RG_VPA_AZC_DELAY_MASK               0x3
#define PMU_RG_VPA_AZC_DELAY_SHIFT              4
#define PMU_RG_VPA_RZSEL_ADDR                   DIG_VCORE_ANA_CON18
#define PMU_RG_VPA_RZSEL_MASK                   0x3
#define PMU_RG_VPA_RZSEL_SHIFT                  6
#define PMU_RG_VPA_ZXREF_ADDR                   DIG_VCORE_ANA_CON18
#define PMU_RG_VPA_ZXREF_MASK                   0xFF
#define PMU_RG_VPA_ZXREF_SHIFT                  8
#define PMU_RG_VPA_HZP_ADDR                     DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_HZP_MASK                     0x1
#define PMU_RG_VPA_HZP_SHIFT                    0
#define PMU_RG_VPA_BWEX_GAT_ADDR                DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_BWEX_GAT_MASK                0x1
#define PMU_RG_VPA_BWEX_GAT_SHIFT               1
#define PMU_RG_VPA_SLEW_ADDR                    DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_SLEW_MASK                    0x3
#define PMU_RG_VPA_SLEW_SHIFT                   2
#define PMU_RG_VPA_SLEW_NMOS_ADDR               DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_SLEW_NMOS_MASK               0x3
#define PMU_RG_VPA_SLEW_NMOS_SHIFT              4
#define PMU_RG_VPA_MIN_ON_ADDR                  DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_MIN_ON_MASK                  0x3
#define PMU_RG_VPA_MIN_ON_SHIFT                 6
#define PMU_RG_VPA_VBAT_DEL_ADDR                DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_VBAT_DEL_MASK                0x3
#define PMU_RG_VPA_VBAT_DEL_SHIFT               8
#define PMU_RG_VPA_MIN_PK_ADDR                  DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_MIN_PK_MASK                  0x3
#define PMU_RG_VPA_MIN_PK_SHIFT                 10
#define PMU_RG_VPA_ZX_TESTMODE_ADDR             DIG_VCORE_ANA_CON19
#define PMU_RG_VPA_ZX_TESTMODE_MASK             0x1
#define PMU_RG_VPA_ZX_TESTMODE_SHIFT            12
#define PMU_RG_VPA_NLIM_SEL_ADDR                DIG_VCORE_ANA_CON20
#define PMU_RG_VPA_NLIM_SEL_MASK                0xF
#define PMU_RG_VPA_NLIM_SEL_SHIFT               0
#define PMU_RG_BUCK_VPA_VREF_TRIM_ADDR          DIG_VCORE_ANA_CON20
#define PMU_RG_BUCK_VPA_VREF_TRIM_MASK          0x1F
#define PMU_RG_BUCK_VPA_VREF_TRIM_SHIFT         4
#define PMU_RG_BUCK_VPA_VREFH_TRIM_ADDR         DIG_VCORE_ANA_CON21
#define PMU_RG_BUCK_VPA_VREFH_TRIM_MASK         0x1F
#define PMU_RG_BUCK_VPA_VREFH_TRIM_SHIFT        0
#define PMU_RG_BUCK_VPA_VREFL_TRIM_ADDR         DIG_VCORE_ANA_CON21
#define PMU_RG_BUCK_VPA_VREFL_TRIM_MASK         0x1F
#define PMU_RG_BUCK_VPA_VREFL_TRIM_SHIFT        5
#define PMU_RG_BUCK_VPA_ZX_OS_REF_TRIM_ADDR     DIG_VCORE_ANA_CON22
#define PMU_RG_BUCK_VPA_ZX_OS_REF_TRIM_MASK     0xFF
#define PMU_RG_BUCK_VPA_ZX_OS_REF_TRIM_SHIFT    0
#define PMU_RG_VPA_RSV1_ADDR                    DIG_VCORE_ANA_CON23
#define PMU_RG_VPA_RSV1_MASK                    0xFF
#define PMU_RG_VPA_RSV1_SHIFT                   0
#define PMU_RG_VPA_RSV2_ADDR                    DIG_VCORE_ANA_CON23
#define PMU_RG_VPA_RSV2_MASK                    0xFF
#define PMU_RG_VPA_RSV2_SHIFT                   8
#define PMU_RG_EN_OT_EXCEPTION_ADDR             DIG_VCORE_ANA_CON24
#define PMU_RG_EN_OT_EXCEPTION_MASK             0x1
#define PMU_RG_EN_OT_EXCEPTION_SHIFT            0
#define PMU_RG_EN_SHIP_ADDR                     DIG_VCORE_ANA_CON24
#define PMU_RG_EN_SHIP_MASK                     0x1
#define PMU_RG_EN_SHIP_SHIFT                    1
#define PMU_RG_WDTRSTB_COLD_EN_ADDR             DIG_VCORE_ANA_CON24
#define PMU_RG_WDTRSTB_COLD_EN_MASK             0x1
#define PMU_RG_WDTRSTB_COLD_EN_SHIFT            2
#define PMU_RG_EN_VBATSNS_ROUT_ADDR             DIG_VCORE_ANA_CON24
#define PMU_RG_EN_VBATSNS_ROUT_MASK             0x1
#define PMU_RG_EN_VBATSNS_ROUT_SHIFT            3
#define PMU_RG_ADC_TS_EN_ADDR                   DIG_VCORE_ANA_CON24
#define PMU_RG_ADC_TS_EN_MASK                   0x1
#define PMU_RG_ADC_TS_EN_SHIFT                  4
#define PMU_RG_TEST_MUXOUT_EN_ADDR              DIG_VCORE_ANA_CON24
#define PMU_RG_TEST_MUXOUT_EN_MASK              0x1
#define PMU_RG_TEST_MUXOUT_EN_SHIFT             5
#define PMU_RG_PMU_DCTEST1_EN_ADDR              DIG_VCORE_ANA_CON24
#define PMU_RG_PMU_DCTEST1_EN_MASK              0x1
#define PMU_RG_PMU_DCTEST1_EN_SHIFT             6
#define PMU_RG_PMU_DCTEST2_EN_ADDR              DIG_VCORE_ANA_CON24
#define PMU_RG_PMU_DCTEST2_EN_MASK              0x1
#define PMU_RG_PMU_DCTEST2_EN_SHIFT             7
#define PMU_RG_PMU_DCTEST3_EN_ADDR              DIG_VCORE_ANA_CON24
#define PMU_RG_PMU_DCTEST3_EN_MASK              0x1
#define PMU_RG_PMU_DCTEST3_EN_SHIFT             8
#define PMU_RG_PMU_DCTEST_SEL_ADDR              DIG_VCORE_ANA_CON24
#define PMU_RG_PMU_DCTEST_SEL_MASK              0xF
#define PMU_RG_PMU_DCTEST_SEL_SHIFT             9
#define PMU_RG_DIG_STRUP_RSV_ADDR               DIG_VCORE_ANA_CON25
#define PMU_RG_DIG_STRUP_RSV_MASK               0xFFFF
#define PMU_RG_DIG_STRUP_RSV_SHIFT              0
#define PMU_RG_PMU_TOP_RSV0_ADDR                DIG_VCORE_ANA_CON26
#define PMU_RG_PMU_TOP_RSV0_MASK                0xFF
#define PMU_RG_PMU_TOP_RSV0_SHIFT               0
#define PMU_RG_PMU_TOP_RSV1_ADDR                DIG_VCORE_ANA_CON26
#define PMU_RG_PMU_TOP_RSV1_MASK                0xFF
#define PMU_RG_PMU_TOP_RSV1_SHIFT               8
#define PMU_RG_PMU_TOP_RSV2_ADDR                DIG_VCORE_ANA_CON27
#define PMU_RG_PMU_TOP_RSV2_MASK                0xFF
#define PMU_RG_PMU_TOP_RSV2_SHIFT               0
#define PMU_RG_STUP_MON_GRP_SEL_ADDR            DIG_VCORE_ANA_CON27
#define PMU_RG_STUP_MON_GRP_SEL_MASK            0x3F
#define PMU_RG_STUP_MON_GRP_SEL_SHIFT           8
#define PMU_RG_STUP_TM_EN_ADDR                  DIG_VCORE_ANA_CON27
#define PMU_RG_STUP_TM_EN_MASK                  0x1
#define PMU_RG_STUP_TM_EN_SHIFT                 14
#define PMU_RG_DIG_STUP_CON_ADDR                DIG_VCORE_ANA_CON28
#define PMU_RG_DIG_STUP_CON_MASK                0xFFFF
#define PMU_RG_DIG_STUP_CON_SHIFT               0
#define PMU_RG_DIG_STRUP_CON0_ADDR              DIG_VCORE_ANA_CON29
#define PMU_RG_DIG_STRUP_CON0_MASK              0xFFFF
#define PMU_RG_DIG_STRUP_CON0_SHIFT             0
#define PMU_RG_DIG_STRUP_CON1_ADDR              DIG_VCORE_ANA_CON30
#define PMU_RG_DIG_STRUP_CON1_MASK              0xFFFF
#define PMU_RG_DIG_STRUP_CON1_SHIFT             0
#define PMU_RG_DIG_STRUP_TEST_CON0_ADDR         DIG_VCORE_ANA_CON31
#define PMU_RG_DIG_STRUP_TEST_CON0_MASK         0xFFFF
#define PMU_RG_DIG_STRUP_TEST_CON0_SHIFT        0
#define PMU_RG_DIG_STRUP_TEST_CON1_ADDR         DIG_VCORE_ANA_CON32
#define PMU_RG_DIG_STRUP_TEST_CON1_MASK         0xFFFF
#define PMU_RG_DIG_STRUP_TEST_CON1_SHIFT        0
#define PMU_RG_DIG_STRUP_TEST_CON2_ADDR         DIG_VCORE_ANA_CON33
#define PMU_RG_DIG_STRUP_TEST_CON2_MASK         0xFFFF
#define PMU_RG_DIG_STRUP_TEST_CON2_SHIFT        0
#define PMU_RG_DIG_STRUP_TEST_CON3_ADDR         DIG_VCORE_ANA_CON34
#define PMU_RG_DIG_STRUP_TEST_CON3_MASK         0xFFFF
#define PMU_RG_DIG_STRUP_TEST_CON3_SHIFT        0
#define PMU_RG_DIG_STRUP_TEST_CON4_ADDR         DIG_VCORE_ANA_CON35
#define PMU_RG_DIG_STRUP_TEST_CON4_MASK         0xFFFF
#define PMU_RG_DIG_STRUP_TEST_CON4_SHIFT        0
#define PMU_RGS_DIG_STRUP_PWR_CON_ADDR          DIG_VCORE_ANA_CON36
#define PMU_RGS_DIG_STRUP_PWR_CON_MASK          0xFFFF
#define PMU_RGS_DIG_STRUP_PWR_CON_SHIFT         0
#define PMU_RGS_VSRAM_EN_ADDR                   DIG_VCORE_ANA_CON37
#define PMU_RGS_VSRAM_EN_MASK                   0x1
#define PMU_RGS_VSRAM_EN_SHIFT                  0
#define PMU_RGS_VPA_OC_STATUS_ADDR              DIG_VCORE_ANA_CON37
#define PMU_RGS_VPA_OC_STATUS_MASK              0x1
#define PMU_RGS_VPA_OC_STATUS_SHIFT             1
#define PMU_RGS_VPA_AZC_ZX_ADDR                 DIG_VCORE_ANA_CON37
#define PMU_RGS_VPA_AZC_ZX_MASK                 0x1
#define PMU_RGS_VPA_AZC_ZX_SHIFT                2
#define PMU_RGS_VPA_AZC_VOS_SEL_ADDR            DIG_VCORE_ANA_CON37
#define PMU_RGS_VPA_AZC_VOS_SEL_MASK            0xFF
#define PMU_RGS_VPA_AZC_VOS_SEL_SHIFT           3
#define PMU_RGS_PMU_RSV1_ADDR                   DIG_VCORE_ANA_CON38
#define PMU_RGS_PMU_RSV1_MASK                   0xFFFF
#define PMU_RGS_PMU_RSV1_SHIFT                  0
#define PMU_RGS_PMU_RSV2_ADDR                   DIG_VCORE_ANA_CON39
#define PMU_RGS_PMU_RSV2_MASK                   0xFFFF
#define PMU_RGS_PMU_RSV2_SHIFT                  0

#endif /* __HAL_PMU_PLATFORM_MT2625_H__ */
