/* Copyright Statement:
 *
 * (C) 2005-2017  MediaTek Inc. All rights reserved.
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. ("MediaTek") and/or its licensors.
 * Without the prior written permission of MediaTek and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 * You may only use, reproduce, modify, or distribute (as applicable) MediaTek Software
 * if you have agreed to and been bound by the applicable license agreement with
 * MediaTek ("License Agreement") and been granted explicit permission to do so within
 * the License Agreement ("Permitted User").  If you are not a Permitted User,
 * please cease any access or use of MediaTek Software immediately.
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT MEDIATEK SOFTWARE RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES
 * ARE PROVIDED TO RECEIVER ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 */

#ifndef __APB_PROXY_AT_CMD_TBL__H__
#define __APB_PROXY_AT_CMD_TBL__H__

#include "apb_proxy.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @brief This structure defines AT command handler structure. For more information, please refer to #at_cmd_hdlr_fp() function.*/
typedef struct {
    char                      *p_cmd_head; /**< AT command string. */
    apb_proxy_at_cmd_handler   cmd_hdlr;   /**< The command handler, please refer to #apb_proxy_event_callback_t. */
    uint32_t                   cmd_id;     /**< The command identifier, will be generated by AP Bridge.*/
} apb_proxy_cmd_hdlr_item_t;

/** @brief This structure defines AT command handler table structure.*/
typedef struct {
    apb_proxy_cmd_hdlr_item_t *p_item_tbl; /**< For more information, please refer to #apb_proxy_cmd_hdlr_item_t. */
    uint32_t                   item_size;  /**< The command item count in the item table. */
} apb_proxy_cmd_hdlr_table_t;

/**********************************************************
 * @brief     get the AT command handler table info.
 * @param[in] None
 * @return    the pointer which points to the AT command handler table info.
 *            The returned pointer is always not NULL.
 **********************************************************/
apb_proxy_cmd_hdlr_table_t *apb_proxy_get_cmd_hdlr_table_info(void);

#ifdef __cplusplus
}
#endif

#endif/*__APB_PROXY_AT_CMD_TBL__H__*/

